### ISSUE TITLE
[TYPO] Old links to Riot/Matrix should be replaced with links to Discord

### ISSUE THREAD

**Issue by aspect0x7bc** [ovrclk/akash#1046]
### Issue type
Typo - old link

### Details
Several places still linking to the [Matrix](https://riot.im/app/#/room/#akashnet:matrix.org) instead of [Discord](https://discord.akash.network).

#### Links
http://akash.network/chat
This url is used in CONTRIBUTING.md - Lines (9, 23, 322). Also in this "community issue template" in the top comment.
(seems like redirecting /chat to go to discord will fix these)

I've also noticed two places on the akash.network website where the Riot/Matrix link is used.
- akash.network/contact/ under "Have a Technical Question?"
- akash.network/validators/ in the footer/bottom section under "Connect with Us Online" before the website footer

**Comment by hydrogen18** [comment]
@aspect0x7bc I'll go over the CONTRIBUTING.md and get it up to date. Thanks for bringing this to our attention.

We're working on updating our website, so the links there should get updated at that time.
