### ISSUE TITLE
single example won't start

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1049]
The single example won't start, I think Cosmos SDK made a logging change. Getting this error when trying to start the example

```
Error: failed to parse log level (main:info,state:info,*:error): Unknown Level String: 'main:info,state:info,*:
```

**Comment by troian** [comment]
yah, i've noticed it yesterday. quick fix is to remove AKASH_LOG_LEVEL config set

**Comment by troian** [comment]
cc @anilCSE

**Comment by anilCSE** [comment]
Yeah, there are some changes to the log levels. Are we missing anything if we remove `AKASH_LOG_LEVEL`?

**Comment by troian** [comment]
Is there any link to whats changed?

**Comment by anilCSE** [comment]
Ref: https://github.com/cosmos/cosmos-sdk/pull/8072
