### ISSUE TITLE
Provider should be able to read kubernetes configuration from anywhere

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1063]
The provider presently only read kubernetes configuration from the user's home directory or an in-cluster configuration.

We should have an optional flag that allows the path to the kubernetes configuration file to specified explicitly.

**Comment by boz** [comment]
it'd also be cool to be able to select a context from the kube config.

I *think* that you might currently be able to set the `KUBECONFIG` environment, but I'm not sure.
