### ISSUE TITLE
remove kind from go.mod

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1071]
We have kind in our go.mod on this line

```
sigs.k8s.io/kind v0.9.0
```

I'm pretty certain this isn't an actual code dependency of ours (some tests use it, but as a binary only). We should remove this from our go.mod file.

**Comment by boz** [comment]
It is a dependency from, `tools.go`, which is how they say to pin binary versions for a project.

**Comment by hydrogen18** [comment]
That seems kind of pointless honestly. Can't we just update our scripts that install development dependencies to fetch the correct version and install it at that time?

**Comment by boz** [comment]
eh, it's a pretty simple way to pin versions without needing to write a bunch of other stuff.

https://github.com/ovrclk/akash/blob/22b45db85d2dd024944e2ce194c432c08c30ca0f/make/setup-cache.mk#L95-L99

**Comment by troian** [comment]
it modifies go.mod/sum. should be fixed in 1.16 https://github.com/golang/go/issues/40276

**Comment by boz** [comment]
can you just run `devdeps-install` locally and update it?
