### ISSUE TITLE
Cannot query my account balance on mainnet

### ISSUE THREAD

**Issue by alexbarta** [ovrclk/akash#1112]
### Issue type

Bug
### Akash version

akash version
v0.9.4-rc9 

### Akash token balance

akash keys list
- name: barta
  type: local
  address: akash1cpd9zmjehs0q0s5hfaqpng4q6v2mw6lpnzz9ah
  pubkey: akashpub1addwnpepqtdkjcjsq6ex9q2z2dgzys7hhcd59sdr6sxsmaftehc7tznc6jt65gl2un3
  mnemonic: ""
  threshold: 0
  pubkeys: []

token balance not working
### What happened
I'm trying to query my account balance on main net
### How to reproduce it

AKASH_NET=https://raw.githubusercontent.com/ovrclk/net/master/mainnet
AKASH_NODE="$(curl -s "$AKASH_NET/rpc-nodes.txt"| head -1)" && echo $AKASH_NODE       
http://rpc.akash.forbole.com:80

akash query account akash1cpd9zmjehs0q0s5hfaqpng4q6v2mw6lpnzz9ah --node  $AKASH_NODE  
Error: error unmarshalling result: unknown field "proof" in types.ResponseQuery
Usage:
  akash query account [address] [flags]

Flags:
      --height int      Use a specific height to query state at (this can error if the node is pruning state)
  -h, --help            help for account
      --node string     <host>:<port> to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
  -o, --output string   Output format (text|json) (default "text")

Global Flags:
      --chain-id string     The network chain ID
      --home string         directory for config and data (default "/Users/alessandrobartalucci/.akash")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors

### Environment

MacOS Catalina 10.15.7

## Next steps

You may [join developer chat](https://akash.network/chat) for community support.

**Comment by boz** [comment]
Hi @alexbarta , you need to be using version 0.8.x with mainnet.

**Comment by alexbarta** [comment]
thanks @boz just installed the cli with brew following the docs. How can I downgrade to 0.8?

**Comment by boz** [comment]
`curl -sSfL https://raw.githubusercontent.com/ovrclk/akash/v0.8.3/godownloader.sh | sh -s -- v0.8.3` will put it in `./bin`.

**Comment by alexbarta** [comment]
bin/akashctl query account akash1cpd9zmjehs0q0s5hfaqpng4q6v2mw6lpnzz9ah --node http://rpc.akash.forbole.com:80

now it works, thanks for your support

**Comment by alexbarta** [comment]
btw @boz is there no way to deploy an app with v0.8 on mainnet? I can't find the subcommands for deployment operations
