### ISSUE TITLE
hostnames still aren't getting released

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1125]
Even after closing a deployment & waiting for it to disappear from the kubernetes cluster you can't reuse a hostname for some reason

You get this error 

```
$ ~/ovrclk/akash/akash provider send-manifest --provider akash1vqthd5lk0rdc67v9v89f7zal6e3e2fw4ejhmfn --keyring-backend=test --from=user0 --home=$PWD/home --node=tcp://147.75.109.209:26657 ./minesweeper_hosts.yaml --dseq 79798
provider error messsage:
hostname not allowed: "minesweeper.hydrogen18.com" already in use
```

The object that tracks the in use hostnames either isn't clearing out state properly, or the deployment manager isn't sending the message to do so

**Comment by boz** [comment]
Sorry for the confusion - I made #1123
