### ISSUE TITLE
provider fees calculation is broken

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1139]
Something we're doing is breaking the provider fee calculation. I keep getting failed bids like this from the mainnet providers 

```
Mar 08 19:11:34 mainnet-ams1-provider-master akash[3315893]: I[2021-03-08|19:11:34.572] broadcast response                           cmp=client/broadcaster response="Response:\n  TxHash: 1296B663CC13AB411D1869A60BCC878A94F69408A1A792BE4477198F7BA72E0E\n  Code: 13\n  Raw Log: insufficient fees; got: 0uakt required: 0uakt: insufficient fee\n  Codespace: sdk" err=null
Mar 08 19:11:34 mainnet-ams1-provider-master akash[3315893]: I[2021-03-08|19:11:34.572] bid complete                                 module=bidengine-order order=akash1vn06ycjjnvsvl639fet9lajjctuturrtx7fvuj/1715/1/1
Mar 08 19:11:34 mainnet-ams1-provider-master akash[3315893]: E[2021-03-08|19:11:34.573] submitting fulfillment                       module=bidengine-order order=akash1vn06ycjjnvsvl639fet9lajjctuturrtx7fvuj/1715/1/1 err="broadcast tx error: response code 13 - (&types.TxResponse{Height:0, TxHash:\"1296B663CC13AB411D1869A60BCC878A94F69408A1A792BE4477198F7BA72E0E\", Codespace:\"sdk\", Code:0xd, Data:\"\", RawLog:\"insufficient fees; got: 0uakt required: 0uakt: insufficient fee\", Logs:types.ABCIMessageLogs(nil), Info:\"\", GasWanted:0, GasUsed:0, Tx:nil, Timestamp:\"\"})"
```

We must be doing this to ourselves, because the other CLI utilities work fine.

**Things known not to work**

Setting env. vars. like this 

```
AKASH_GAS=auto
AKASH_GAS_PRICES=0.025uakt
AKASH_GAS_ADJUSTMENT=4.5
```

Setting these env. vars

```
AKASH_FEES=6123uakt
```

**Things known to work***

Adding `--fees=5123uakt` to the command line

**Comment by arno01** [comment]
remek's got the same issue when using `--gas=auto` https://discord.com/channels/747885925232672829/771909807359262751/949327496799739905

I think, IIRC, I have been getting the same.

Looks like the only solution is not to use `--gas=auto` and either use static `--fees` (minimum 5000uakt) as explained here https://discord.com/channels/747885925232672829/771909807359262751/949423492179296336

or, since `--fees` & `--gas` cannot be specified together, the following is also working:

```
AKASH_GAS_PRICES=0.025uakt
AKASH_GAS=200000
```

**Comment by hydrogen18** [comment]
@arno01 this is fixed with your patches right?

**Comment by arno01** [comment]
@hydrogen18 right, fixed in the v0.14.2-rc1. (There is also v0.14.2-rc2 I've just noticed)

When can it get officially released?
As v0.14.1 has basically stopped working without that fix no matter how high you set the scalar gas value to.

**Comment by troian** [comment]
@arno01 there are a few more things we want to get into `v0.14.2`. you can rely on `v0.14.2-rc2`

**Comment by boz** [comment]
@arno01 if you use `v0.14.2-rc2`, you *must* run this first: https://github.com/ovrclk/infra-ops/blob/a74edcca530d888b7ee2e7b9cf73c7fb2499008b/roles/akash-provider-run/templates/orphan-manifest-purge

**Comment by arno01** [comment]
> @arno01 if you use `v0.14.2-rc2`, you _must_ run this first: https://github.com/ovrclk/infra-ops/blob/a74edcca530d888b7ee2e7b9cf73c7fb2499008b/roles/akash-provider-run/templates/orphan-manifest-purge

@boz I don't have an access to https://github.com/ovrclk/infra-ops

**Comment by boz** [comment]
here you go @arno01:

```sh
#!/usr/bin/env bash

kubectl get mani -n lease -o 'custom-columns=name:{.metadata.name}' --no-headers | \
  while read ns; do

    # if ns exists, it's a fresh manifest.
    if kubectl get ns "$ns" >/dev/null 2>&1; then
      echo "FOUND: $ns"
      continue
    fi

    # make sure it's a NotFound error before deleting.
    nserr=$(kubectl get ns "$ns" 2>&1)
    if [[ "$nserr" == *NotFound* ]]; then
      echo "GONE: $ns"
      kubectl delete mani "$ns" -n lease
      continue
    fi
  done
```

**Comment by hydrogen18** [comment]
@troian your changes to make auto work should have fixed this right?

**Comment by troian** [comment]
correct
