### ISSUE TITLE
cli: oseq, gseq: default to 1

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1143]
use `1` as a default value for `--oseq` and `--gseq`.

**Comment by boz** [comment]
The following command, for instance, should work fine:

```sh
akash tx market lease create --provider akash1f6gmtjpx4r8qda9nxjwq26fp5mcjyqmaq5m6j7 --from foo                             
Error: required flag(s) "dseq", "gseq", "oseq", "owner" not set
```

**Comment by gosuri** [comment]
It'll be good to set the default owner as the address from the key specified with `--from` flag. What do you think @boz?

**Comment by troian** [comment]
we should already have it implemented for some commands, have to extend it to all
