### ISSUE TITLE
brew: support for mac m1 (arm)

### ISSUE THREAD

**Issue by gosuri** [ovrclk/akash#1166]
Currently, homebrew defaults all mac OS systems to `amd64` and ignores M1. Adding `arm64` fixes this. Request from [twitter](https://twitter.com/Atomzwieback/status/1371208128738512898/photo/1).

![EweChbZXEAwQEx9](https://user-images.githubusercontent.com/70293/111084553-5c8e2d00-84e9-11eb-98ad-164159ccf806.jpg)

**Comment by troian** [comment]
we don't have m1 build yet. i'll check if goes quickly through docker-cross
