### ISSUE TITLE
ability to query pricing before creating order

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1167]
The client should be able to ask providers if the max price is acceptable to them.  Extending this, a bit further, we can have a `/validate` endpoint that validates not only price but everything else.

The flow would then be:

1. client queries a sample of providers that match its requirements from the blockchain.
2. client queries each provider in the sample to see if the provider will accept their group spec.
3. if **2.** passes, create the deployment.  If **2.** fails, exit with error message from providers.

**Comment by hydrogen18** [comment]
We may want to consider rate limiting this in the future, since providers may run a shell script for pricing. Abusing this provider endpoint could be a way to denial of service attack a provider.
