### ISSUE TITLE
provider should close bid on deployments stuck in ImagePullBackoff

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1170]
If the provider has a deployment stuck in ImagePullBackoff state, then it should close the lease after some amount of time. Such a deployment isn't going to work. Just send an event so that the data can be picked up and be done with it.

**Comment by boz** [comment]
Doesn't it effectively already do this?

**Comment by hydrogen18** [comment]
It may, but something must stop it from happening. There is at least one that has spent 4.5 days in that state
![Screenshot from 2021-03-19 11-04-34](https://user-images.githubusercontent.com/130230/111809376-ec91f500-88a2-11eb-81df-66c47d3e2f48.png)
![Screenshot from 2021-03-19 11-03-39](https://user-images.githubusercontent.com/130230/111809377-ed2a8b80-88a2-11eb-9c02-0d04dca2f073.png)

**Comment by boz** [comment]
If the healthchecks fail then it should kill the bid/lease.

**Comment by hydrogen18** [comment]
Will need to doublcheck to see if this is just a deployment that did not get clean up then.

**Comment by hydrogen18** [comment]
I haven't been able to reproduce this, I think this was caused by another bug & this deployment also happened to be busted. In other words it was just an orphan deployment & it was broken.
