### ISSUE TITLE
Fractional uakt bid pricing

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1174]
The AKT token price has gotten high enough that a 1 uakt per block bid can be pretty pricey on a daily basis. For small deployments this is a problem.

Bid prices need to be capable of being expressed in fractional uakt, use the decimal coin type.

We'll need to do the following

1. Convert the protobuf for bid pricing to use `DecCoin` instead of `Coin`
2. Convert the protobuf for payments (part of escrow) to use `DecCoin` instead of `Coin`
3. Allow the manifest to specify fractional uakt
4. Only settle an escrow payment when it is >1 uakt. Since this still needs to be settled in whole uakt, payments are going to be tracked to "fractional block height" where this fractional height is less than the current block height during settlement. The combination of fractional uakt and fractional block height settlement (tracked on a per payment basis) gives us whole uakt which can be deducted from the escrow account.
5. Do a cosmos upgrade to convert the blockchain over, the basic explanation of this is here https://pkg.go.dev/github.com/cosmos/cosmos-sdk/x/upgrade
6. When a deployment is closed or a lease terminates, check to see if the escrow account has ever made a payment. If it hasn't, make sure the end-of-lease settlement pays at least 1uakt. This prevents deployment abuse that could give "free" delployments.

**Comment by hydrogen18** [comment]
@boz Thoughts on what I've outlined here?

**Comment by boz** [comment]
Looks good.  Some thoughts on escrow:

Settlement happens for basically any operation that modifies an escrow account or its payments.  It "moves" tokens from the account to the payment object such that everything is calculated up to the block during which the settlement is running.

If a new payment is added, from a new lease for instance, we _have_ to settle.  Unless everything is done in a different way of course.

I think that a reasonable way to do it would be to keep things in `DecCoin` until withdraw.  For instance, have `Payment.Balance` be a `DecCoin` but have `Payment.Withdrawn` be a `Coin` https://github.com/ovrclk/akash/blob/aa2ad8a31a37bc9a63f109a9fd4cc7763946d388/x/escrow/keeper/keeper.go#L189-L190

This way partial `uakt` can accumulate in `Payment.Balance` over multiple account settlements.

When a payment is closed, any un-transferred `Payment.Balance` (note: it should be less than `1uakt`) can be "transferred" back to the `Account.Balance` (removed from `Account.Transferred`).

Thoughts?

**Comment by hydrogen18** [comment]
Yeah, that might be an easier strategy to implement

**Comment by ngehani** [comment]
What's remaining to get this feature released?

**Comment by boz** [comment]
@ngehani
 
* #1201 needs to be reviewed
* We need to decide on a minimum bid/lease amount
* Lots of testing
* This is a state-changing feature and will require a network upgrade.

**Comment by ngehani** [comment]
> We need to decide on a minimum bid/lease amount

Like whether it should be 0.1 vs 0.01? What's criteria should we use for this decision?

**Comment by boz** [comment]
> > We need to decide on a minimum bid/lease amount
> 
> Like whether it should be 0.1 vs 0.01? What criteria should we use for this decision?

Yeah.

Since wallets work with whole `uakt`, opening a lease means that you will pay, at a minimum, 1 `uakt`.

This feature allows for bids to be for less than 1 uakt.  If a bid is for 0.5 `uakt`, you will be over-paying if you close the lease after an odd number of blocks - the amount paid is rounded up to an integer `uakt`.

So we need to decide how much over-payment is reasonable to allow.

Let's not over-analyse this - "over paying" means paying an extra `uakt` *max*, which is currently something like $0.00005 USD.  With 1 AKT = $1000 USD, over-paying still means paying an extra $0.05 at a maximum.

If nothing else I'd say let's get ourselves two orders of magnitude in pricing flexibility - set a minimum bid price of 0.01 `uakt`.

**Comment by ngehani** [comment]
Alright, decided then: `MinUnitPrice: 0.01` :-)

**Comment by hydrogen18** [comment]
@boz  Is it possible to target a network upgrade of August 9th for this? That should give us a while to finish up the code on this, write a proposal, & then wait for the voting period.

**Comment by boz** [comment]
> @boz Is it possible to target a network upgrade of August 9th for this? That should give us a while to finish up the code on this, write a proposal, & then wait for the voting period.

I think so.  I'm so sorry this has taken so long.  Putting a date on it will help force the issue.

That being said, with the date I think it may need to be out a bit longer - I think we should do an actual testnet for v0.14 before we start a voting period.  Let's make it a point to start putting a plan together with @ngehani .

**Comment by hydrogen18** [comment]
This was part of the 0.16.x release
