### ISSUE TITLE
goreleaser publishes prerelease to prod brew

### ISSUE THREAD

**Issue by troian** [ovrclk/akash#1191]
version in output below should be `v0.10.2`

```
❯ brew info akash
ovrclk/tap/akash: stable 0.12.0-rc1
Blockchain-powered decentralized compute platform
https://akash.network
/usr/local/Cellar/akash/0.12.0-rc1 (3 files, 69.3MB) *
  Built from source on 2021-03-24 at 11:02:20
From: https://github.com/ovrclk/homebrew-tap/blob/HEAD/akash.rb
```

**Comment by greycr0w** [comment]
Im having the same issue and when issuing simple commands such as
`akash version`

I get the following error:

`Error: failed to parse log level (main:info,state:info,statesync:info,*:error): Unknown Level String: 'main:info,state:info,statesync:info,*:error', defaulting to NoLevel`

**Comment by boz** [comment]
You have some stale configuration.   Edit `~/.akash/config/config.toml` and set

```toml
log_level = "info"
```
