### ISSUE TITLE
provider api: better errors on invalid cert

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1207]
The error returned by `send-manifest` when the user has an invalid (revoked in this case) cert is:

```
Error: Put "https://provider.sjc1p0.mainnet.akashian.io:8443/deployment/477826/manifest": EOF
```

It should be more informative.

**Comment by troian** [comment]
looks like errors returned by `VerifyPeerCertificate` are not returned properly during TLS handshake

**Comment by ngehani** [comment]
We should have a RPC node for each region. It comes in pairs. @hydrogen18 hitting forboles RPC node. 

@troian - Please document what you said on the sprint planning call here so we have the full context of the workflow and potential issues, and workarounds.

**Comment by troian** [comment]
TLS handshake errors may come from 2 places
- client: if handshake fails here that returns well formatted error with explanation of what caused to terminate
- server: if `VerifyPeerCertificate` errors client only receives alert during TLS handshake and always returns `remote error: tls: bad handshake` regardless to what was actually cause of termination.

reason for recent failures was triggered during query of certificate from chain on server side during TLS handshake and as pointed [in](https://github.com/ovrclk/akash/issues/1207#issuecomment-831393064) RPC node running in private mode alongside with each provider may fix they issue.

closing for now. reopen/create if solution above does not help
