### ISSUE TITLE
Staking key with limited authority

### ISSUE THREAD

**Issue by thecryptodrive** [ovrclk/akash#1212]
**Is your feature request related to a problem? Please describe.**
The current problem is that it isn't easy to automate claiming and staking without exposing your main key on a public-facing server

**Describe the solution you'd like**
The solution would be to have a different set of private and public keys which could be called Staking or Rewards keys, these would only have authority to claim rewards and stake rewards. It would not have authority for transfers or unbonding. 

**Additional context**
Multi-key blockchains such as Steem, Hive and Blurt are an example of this.

Here is an example of a multi-layer set of public keys on one of the aforementioned chains:

![image](https://user-images.githubusercontent.com/22358264/114667100-2b588500-9d53-11eb-958d-58e4da678062.png)

**Comment by boz** [comment]
Thanks @thecryptodrive.  This would be great to have, and we're looking at ways to add it to the Akash marketplace operations.

That said, regarding withdrawing and staking, it'd be best to submit this request to github.com/cosmos/cosmos-sdk .

For what it's worth, one option for automating on an external server is to pre-sign a ton of withdraw transactions then just broadcast them from a public node.

**Comment by thecryptodrive** [comment]
Thanks for the advice, I have created an issue on the cosmos-sdk https://github.com/cosmos/cosmos-sdk/issues/9120

@boz do you know of any existing opensource code for claiming and delegating AKT rewards?

**Comment by thecryptodrive** [comment]
@boz check this out https://github.com/cosmos/cosmos-sdk/issues/9120 seems they have a new xAuthz feature coming in ver 0.43

**Comment by boz** [comment]
@thecryptodrive - Amazing; will do.  Thanks!
