### ISSUE TITLE
Wrong version tag in version.txt for mainnet

### ISSUE THREAD

**Issue by andynog** [ovrclk/akash#1213]
Following the guide to run a full node https://docs.akash.network/guides/install

I believe the file https://github.com/ovrclk/net/blob/master/mainnet/version.txt has the wrong version tag should be `v0.12.1` instead of just `0.12.1` because the curl command fails to fetch it.

**Comment by boz** [comment]
Thanks @andynog.  I'm fixing by adding a `v` prefix to the shell examples for now.  The current scheme is in too many scripts, we'll need to do a pass and get them all at once sometime.
