### ISSUE TITLE
Allow hyphen in domain name

### ISSUE THREAD

**Issue by zJuuu** [ovrclk/akash#1218]
Using a hyphen in a domain name results in a error: invalid manifest: service "test" has invalid hostname "test-test.com" even if i try to use it as string

**Comment by rav-11** [comment]
This looks like a typo in the regex, should be a quick fix. As per the contributing doc, I won't do a PR, but let me know if it would be helpful.

validation/manifest.go line 19, the hyphen needs to be escaped i.e. change like this:
From:
        hostnameRegex              = regexp.MustCompile(`^[[:alnum:],-,\.]+\.[[:alpha:]]{2,}$`)
To
        hostnameRegex              = regexp.MustCompile(`^[[:alnum:],\-,\.]+\.[[:alpha:]]{2,}$`)
