### ISSUE TITLE
Add prometheus listener HTTP endpoint in provider

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1221]
We should be able to start the prometheus metrics listener with the existing HTTP endpoints 

e.g.  https://github.com/tendermint/tendermint/blob/master/node/node.go#L1653

Go through the provider code that manages the lifecycle of a lease (from bid, to deployment, to closure, etc.) and add relevant metrics that can get exported via this. Also would be nice to see how often the provider submits a TX & submits for settlement

**Comment by boz** [comment]
Sorry, I forget which PR addresses this - mind throwing a `fixes ovrclk/akash#1221` in it?
