### ISSUE TITLE
Simplify Readme / Build / Quickstart

### ISSUE THREAD

**Issue by faddat** [ovrclk/akash#1222]
### Issue type

Readme.md isn't ideal

### Akash version

N/A

### What happened

The build did not build :)

### How to reproduce it
Uncertain, might have been `go env` related, but fact is it's going to be more reliable for people to `git clone` then `make`

**Comment by faddat** [comment]
#1223 

Might not fully close this, but it's a good start.

**Comment by faddat** [comment]
Should add some deploy snippets and try to get deploys made easier, perhaps by wrapping the existing deploy tooling.

**Comment by hydrogen18** [comment]
PR has been merged, thanks for the contribution
