### ISSUE TITLE
production: containers running after lease closed

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1227]
Seems to be affecting vanity url locks as well.  Report from user `tombeyond` on discord:

> I think there's some cases where deployments are closed but the container keeps running
> I'm testing with akashhw.tombeynon.co.uk which is giving that error, closed a few hours ago but it's still up at both the vanity > domain and the akash domain (http://8lim5k05ft9bhdm12vpvrghcr8.ingress.ewr1p0.mainnet.akashian.io/)
> I also closed a node a few days ago which still seems to be running - > http://176ddd8tk9827439rjnl09es0g.ingress.ewr1p0.mainnet.akashian.io:32006/status. I closed another at the same time and > that one did shut down properly
> So I guess if the container is still up + the domain still linked, that might be causing the no global services issue on new deploys as 80 can't be mapped

**Comment by troian** [comment]
one of cases when it may happen is unreachable k8s cluster. @tombeynon reported a dangling lease workload and it has lots of kube connect errors.
```
manifest-group=dcloud cmp=deployment-monitor err="kube: internal error: Get \"https://147.75.199.187:6443/api/v1/namespaces/d5avkhet9f3e3jcr7omtdo9cm665fsbme3qnhc02j1soc\": dial tcp 147.75.199.187:6443: connect: connection refused"
```

lease manager retries teardown [50 times](https://github.com/ovrclk/akash/blob/4ce6a0a8ef7aa29883b00f2402e41c6ef0011ba4/provider/cluster/manager.go#L257)  and gives up, which might be a case if k8s is unreachable

**Comment by boz** [comment]
ovrclk/operations#40 is a good catch-all for these kinds of things

**Comment by troian** [comment]
closing as issue was described in the [comment](https://github.com/ovrclk/akash/issues/1227#issuecomment-828439599).
