### ISSUE TITLE
production: error when querying lease status

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1229]
> I am unable to query lease status, is there an issue on the provider end?
> Error: Get "https://provider.sjc1p0.mainnet.akashian.io:8443/lease/$dseq/1/1/status": dial tcp 147.75.109.243:8443: connect: connection refused

They used their actual `dseq`.  it's not clear to me why the deployment owner is not in the url - did they take it out maybe?

**Comment by troian** [comment]
provider endpoints are fetching owner from certificate. i'll check why there are double slash

**Comment by boz** [comment]
how does it know which cert to look up if it can't uniquely identify the deployment?

**Comment by troian** [comment]
client certificate sent during TLS handshake

**Comment by boz** [comment]
it wasn't missing - they removed it when reporting

**Comment by boz** [comment]
> client sends certificate during TLS handshake

the owner address is then looked up by cert hash?

**Comment by troian** [comment]
server pulls owner address from CommonName field in the certificate

**Comment by boz** [comment]
> server pulls owner address from CommonName field in the certificate

Ok.  Then it's looked up from the chain?

**Comment by troian** [comment]
Partially, certificate received from TLS handshake is then being validated on chain (serial # exists, valid, not expired, signed by same key etc) then CommonName (containing owner address) extracted

**Comment by boz** [comment]
but couldn't someone make a cert with CommonName being someone else's address?

**Comment by troian** [comment]
it can be done, but in order to pass they have to be signed bu same key

**Comment by troian** [comment]
with error `connect: connection refused` most probably provider was restarted by us due to maintenance.
