### ISSUE TITLE
'Deployment exists' error 

### ISSUE THREAD

**Issue by namelessperson0** [ovrclk/akash#1238]
I am running the below command 
` akash tx deployment create deploy.yml`
I am getting `Deployment exists` error.
I have closed the previous deployment though.

**Comment by troian** [comment]
you have to use another `dseq` value.
`akash tx deployment create` is actually `akash tx deployment create --dseq=1`
so each deployment must have unique `dseq` value

**Comment by namelessperson0** [comment]
> you have to use another `dseq` value.
> `akash tx deployment create` is actually `akash tx deployment create --dseq=1`
> so each deployment must have unique `dseq` value

Thanks :)
Where is the corresponding documentation for what you mentioned? In https://docs.akash.network/guides/deploy#create-the-deployment there is no mention that dseq needs to be supplied in creating deployment.

**Comment by boz** [comment]
> you have to use another `dseq` value.
> 
> `akash tx deployment create` is actually `akash tx deployment create --dseq=1`
> 
> so each deployment must have unique `dseq` value

this is not true.   the default value of `--dseq` is or should be the current block height.

**Comment by boz** [comment]
@namelessperson0 : do you have an `AKASH_DSEQ` environment variable?

**Comment by daniel-farina** [comment]
I also had issue with these steps as they were not documented. Once I figure all this out I'll submit some PR to fix the documentation.
