### ISSUE TITLE
Error when creating new deployment

### ISSUE THREAD

**Issue by Guillembonet** [ovrclk/akash#1239]
### Issue type

Bug

### Akash version

v0.12.1

### Akash token balance

balances:
- amount: "9388694"

### What happened
I created a deployment, deleted it and tried to create another deployment using:
`akash tx deployment create deploy.yml --from $AKASH_KEY_NAME --node $AKASH_NODE --chain-id $AKASH_CHAIN_ID --fees 5000uakt -y`
and got the following error:
`{"height":"796389","txhash":"C0B19A57900E0A0C2D0083F7CDF4A10DC8E739A36DF3F8BB3852DE745A0BA50C","codespace":"deployment","code":3,"data":"","raw_log":"failed to execute message; message index: 0: Deployment exists","logs":[],"info":"","gas_wanted":"200000","gas_used":"53410","tx":null,"timestamp":""}`

### What did you expect to happen
A new deployment is created with a new generated dseq

### How to reproduce it

run `akash tx deployment create deploy.yml --from $AKASH_KEY_NAME --node $AKASH_NODE --chain-id $AKASH_CHAIN_ID --fees 5000uakt -y`, if its the first deployment it works otherwise I get this error.

### Environment

akash (server): mainnet
akash (client): Linux 5.8.0-50-generic #56~20.04.1-Ubuntu
env variables set to:
- export AKASH_KEYRING_BACKEND=os
- export AKASH_NET="https://raw.githubusercontent.com/ovrclk/net/master/mainnet"
- export AKASH_NODE="$(curl -s "$AKASH_NET/rpc-nodes.txt" | shuf -n 1)"
- export AKASH_ACCOUNT_ADDRESS=akash12ljk9qgl9zlpchwwywlag3c7yz75rzjlp4m9e9
- export AKASH_CHAIN_ID="$(curl -s "$AKASH_NET/chain-id.txt")"
- export AKASH_VERSION="$(curl -s "$AKASH_NET/version.txt")"

### Anything else we need to know?

deployment yaml is wordpress from awesome-akash repo with attributes modified to match tutorial example. (just modified host and signedBy)

**Comment by Guillembonet** [comment]
@troian and I spoke about it on discord #deployments channel

**Comment by troian** [comment]
you have set `AKASH_DSEQ=796389` in env somewhere
to check it `env | grep AKASH_DSEQ`
