### ISSUE TITLE
One-Liner

### ISSUE THREAD

**Issue by faddat** [ovrclk/akash#1256]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to run more than one command to run a full/seed node.

**Describe the solution you'd like**
A docker image that's ready to go

**Describe alternatives you've considered**
Bash scripts

https://github.com/galaxypi/galaxy

**Additional context**
#1255

**Comment by hydrogen18** [comment]
Hello, automation like this is outside the scope of this project at this time.

**Comment by faddat** [comment]
in fact, it is not super great, thanks for closing!
