### ISSUE TITLE
KubeVirt

### ISSUE THREAD

**Issue by faddat** [ovrclk/akash#1258]
**Is your feature request related to a problem? Please describe.**
Sometimes my less tech savvy colleagues will say that it's not possible to start a server on akash They actually mean a virtual machine.

**Describe the solution you'd like**
Let's use KubeVirt to allow akash to provide virtual machines.

**Describe alternatives you've considered**
Everyone could build everything in containers, but not everything fits properly in a container, and not everybody wants that.

**Comment by hydrogen18** [comment]
Hello @faddat we do not anticipate supporting VMs at this time.

**Comment by faddat** [comment]
No objection;

Do you mind if I ask why not?
