### ISSUE TITLE
Allow remote shell access into existing deployments

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1259]
The Akash CLI should somehow allow remote access into existing deployments with a shell. This should work by just having the CLI talk to the provider and tunnel access through there.

**Comment by ngehani** [comment]
`kubectl` as reference ?

**Comment by boz** [comment]
> `kubectl` as reference ?

just how it's implemented - IIRC it uses the Kubernetes API to get TTY access, and we can do the same.
