### ISSUE TITLE
Deployment DSEQ 827274 fingerprint and ports changed after 3 days

### ISSUE THREAD

**Issue by lightiv** [ovrclk/akash#1260]
### Issue type
BUG

### Akash version

v0.12.1

### Akash token balance

balances:
- amount: "1100765829"
  denom: uakt

### What happened

After 3 days the following deployment's node fingerprint and external ports change.  This leads me to believe that the container is periodically being recreated.  Original deployment was 05/19/2021.  The problem occurred the night 05/21/2021 into 05/22/2021

This deployment is a "Gravity Bridge Testnet 2 Validator Deployment"

```DSEQ 827274 from account address: akash14s4tlmlvy0vsps05csf8l80m7nqxmau38tehp9```

Original ports were:
```
http://gravity-bridge.paullovette:31059/status 
http://gravity-bridge.paullovette.com:31059/status 
```
Current ports are:
``` 
http://gravity-bridge.paullovette:30032/status 
http://gravity-bridge.paullovette.com:30032/status 
```

### What did you expect to happen

Fingerprint and Ports to not change once the manifest is deployed by the provider.

### How to reproduce it
Periodically try to access the current links above which are working as of posing this issue.  As noted above the problem occurred after 3 days. 

### Environment

Deploying from Ubuntu Linux 20.04 in an Oracle VirtualBox on Windows 10

## Next steps

You may [join developer chat](https://akash.network/chat) for community support.

**Comment by lightiv** [comment]
I just caught this today but I think it is indeed every three days the deployment fingerprint and ports are changing:

New port for 26657: (the others also changed)

http://gravity-bridge.paullovette.com:32416/status

**Comment by tombeynon** [comment]
I have been noticing this as well. The ephemeral ports change during a running deployment. I can understand them changing when you update the deployment (although this is challenging in itself) but changing during a running deployment is pretty difficult to manage. 

Is this likely to be looked at soon? It impacts how we're advising people to integrate with Akash. If the ports can change at any time, it's pretty impossible to use Akash for anything other than port 80 hosting.

**Comment by tombeynon** [comment]
Luckily I've managed to take some screenshots of the deploy tool that outlines this issue.

Deployments yesterday. Note DSEQ **1397104** - port **32316**:

![Screenshot 2021-06-17 at 12 09 25](https://user-images.githubusercontent.com/670623/122387751-196bac00-cf67-11eb-9486-0127bed2273a.png)

Deployments today. Note DSEQ **1397104** - port **30407**:

![Screenshot 2021-06-17 at 12 10 20](https://user-images.githubusercontent.com/670623/122387803-27213180-cf67-11eb-8ace-aa9aebc34aba.png)

The same deployment with the changed port, but showing `observed_generation` as 1, so a new container hasn't been started at any point:

![Screenshot 2021-06-17 at 12 15 39](https://user-images.githubusercontent.com/670623/122387920-46b85a00-cf67-11eb-8734-a4a0a17cf519.png)

2 of the 4 deployments changed ports. Interestingly also the only two that had escrow charges, even though they're all running the same config
