### ISSUE TITLE
Deployment Create reads AKASH_DSEQ from environment and fails

### ISSUE THREAD

**Issue by sarasioux** [ovrclk/akash#1284]
### Issue type

Bug

### Akash version
v0.12.2-rc4

### Akash token balance

24305732

### What happened
If I have AKASH_DSEQ set in my environment (from a previous deployment), running the akash tx deployment create command again will fail with the error:
``failed to execute message; message index: 0: Deployment exists``

### What did you expect to happen
The command should only use a value that is passed on the command line, i.e. --dseq, and should not invisibly read and use environment variables in its logic.

I expected that my new deployment would succeed regardless of leftover environment variables from the old deployment.

### How to reproduce it

``
export AKASH_DSEQ=1404345
``
``
akash tx deployment create ./deploy.yml --from $AKASH_KEY_NAME --node $AKASH_NODE --chain-id $AKASH_CHAIN_ID --fees 5000uakt -y
``

Be sure to set AKASH_DSEQ to something you actually deployed on already.

### Environment

Mainnet
Mac OSX

## Next steps

You may [join developer chat](https://akash.network/chat) for community support.

**Comment by boz** [comment]
Hi @sarasioux,

That is by design - flags are read from environment variables.

In fact you can simplify your workflow by exporting the often-used flags.

**Comment by sarasioux** [comment]
Well that's somewhat unfortunate, since it was a very difficult problem to debug as a new user.  I now have "unset AKASH_DSEQ" in my muscle memory, but for other new users maybe an alternative solution is to make the message more clear, i.e.:  Deployment with dseq 1234 already exists.  That might jog someone's memory to check their environment variables and shortcut a very long night of debugging.

**Comment by boz** [comment]
:+1: we should do a better job at displaying what the setting sare.

For what it's worth, manually-set flags takes precedence over environment variables.  The "default" DSEQ happens to be the current block height, so that one is a bit of an outlier.
