### ISSUE TITLE
Fix and ensure successful operations with "Single" Dev environment deployment config

### ISSUE THREAD

**Issue by 0x0I** [ovrclk/akash#1287]
Deployment of a "[Single](https://github.com/ovrclk/akash/tree/v0.10.2/_run/single)" dev environment configuration currently fails (due to reasons set to be described in this issue).

This task entails identifying and resolving all deployment and general operational errors in order to aid in developer/community testing and other development processes.

**Comment by 0x0I** [comment]
Within [Setup](https://github.com/ovrclk/akash/tree/master/_run/single#setup), `make devdeps-install` Makefile DIRECTIVE doesn't appear to exist within config's root DIR or throughout akash repo.

**Comment by 0x0I** [comment]
`NODE_HOME` + `CLIENT_HOME` environment variables should be set prior to executing the `kustomize-init` Make step.

Values seem to both refer to the user's Akash HOME cache directory (e.g. `~/akash/.cache/run/single`). Note: both were previously set in *common.mk* as of [v0.10.2](https://github.com/ovrclk/akash/blob/v0.10.2/_run/common.mk).

**Comment by 0x0I** [comment]
Local (to deploy host) Akash binary is expected based on `make kustomize-init-provider`'s keys export step and its use of the `AKASHCTL_NONODE` envvar.

`AKASHCTL_NONODE` isn't set throughout the source from what I can tell and has no default value.

**Comment by hydrogen18** [comment]
Anything `AKASHCTL_` isn't read anymore anymore by the code We used to have a separate command called `akashctl`, but that was removed a while back.

**Comment by 0x0I** [comment]
Oh ok got it. Looks like its usage in the provider's init should be replaced then by a path to a known local Akash binary (e.g. using something like`AKASH_DEVCACHE_BIN` or maybe just `AKASH` - as referenced in make/init.mk).

**Comment by troian** [comment]
let me check this thing, i might some typo when introduced direnv
