### ISSUE TITLE
--log_format "json" does not comply

### ISSUE THREAD

**Issue by gotjoshua** [ovrclk/akash#1302]
### Issue type
Bug

### Akash version
v0.12.2-rc5

### Akash token balance
$ akash key list #returns your key names and values
```
akash key list                                                                                                                                            16:53:39
Error: unknown command "key" for "akash"

Did you mean this?
	keys

Run 'akash --help' for usage.
```
`akash query account akash15gjha2fx86meaare45nqh43dpgyr4ssg9a9zxr `
```
                                                                                                                               
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "20027"
address: akash15gjha2fx86meaare45nqh43dpgyr4ssg9a9zxr
pub_key:
  '@type': /cosmos.crypto.secp256k1.PubKey
  key: A5XyfiPQSmtYk0nPxI5B7mh3wsipGbtwSWX8uXApY7sl
sequence: "50"
```

### What happened
`akash query deployment list --log_format=json `
  .. **and** .. 
`akash query deployment list --log_format "json"  `   
both return plain text instead of json

### What did you expect to happen
command returns json as requested ( so i can pipe through jq and filter and stuff )

### Environment
mac os cli

**Comment by boz** [comment]
Hi @gotjoshua - use `-o json` for JSON output.   The flag you're using is for something else.

**Comment by gotjoshua** [comment]
thanks... 

_but_ can we make a new issue or use this one to acknowledge that the cli documentation needs updating?

```
akash query deployment -h

Global Flags:
      ...
      --log_format string   The logging format (json|plain) (default "plain")
      ...
```

-o is nowhere to be found

**Comment by gotjoshua** [comment]
https://github.com/ovrclk/docs/pull/211
