### ISSUE TITLE
Whitepaper link on the github repo is broken

### ISSUE THREAD

**Issue by arijitAD** [ovrclk/akash#1310]
* https://github.com/ovrclk/akash/blob/master/README.md#akash---decentralized-serverless-network
* https://akash.network/l/whitepaper
* https://akash.network/research

Blog link is broken:
* https://github.com/ovrclk/akash/blob/master/README.md#official-blog-and-documentation

**Comment by ngehani** [comment]
@olivekimoto - Can you please get these fixed on the website? Thanks!

**Comment by dmikey** [comment]
Nothing for @olivekimoto to do, I believe these are all GitHub changes, whitepaper and research was removed per greg.

**Comment by ngehani** [comment]
Yeah, so the links and references to it will be removed on the next push?

**Comment by boz** [comment]
> Nothing for @olivekimoto to do, I believe these are all GitHub changes, whitepaper and research was removed from website per greg.

Do we have the WP hosted _somewhere_ or are we not offering it anymore?

We get some support issues on intercom asking for it.

Happy with either way, just want to figure out a response.

**Comment by ngehani** [comment]
@olivekimoto - We can move the White Papers to internal google drive and provide links from Notion for internal history - where we came from kinda thing. We now have a working product as Greg says so we don't need this on the public website.

**Comment by dmikey** [comment]
> > Nothing for @olivekimoto to do, I believe these are all GitHub changes, whitepaper and research was removed from website per greg.
> 
> Do we have the WP hosted _somewhere_ or are we not offering it anymore?
> 
> We get some support issues on intercom asking for it.
> 
> Happy with either way, just want to figure out a response.

No I don't think we've got this serving anywhere at all right now. Maybe it's something to put int he gitbook docs?

**Comment by boz** [comment]
> > > Nothing for @olivekimoto to do, I believe these are all GitHub changes, whitepaper and research was removed from website per greg.
> > 
> > 
> > Do we have the WP hosted _somewhere_ or are we not offering it anymore?
> > We get some support issues on intercom asking for it.
> > Happy with either way, just want to figure out a response.
> 
> No I don't think we've got this serving anywhere at all right now. Maybe it's something to put int he gitbook docs?

**Comment by boz** [comment]
> > > Nothing for @olivekimoto to do, I believe these are all GitHub changes, whitepaper and research was removed from website per greg.
> > 
> > 
> > Do we have the WP hosted _somewhere_ or are we not offering it anymore?
> > We get some support issues on intercom asking for it.
> > Happy with either way, just want to figure out a response.
> 
> No I don't think we've got this serving anywhere at all right now. Maybe it's something to put int he gitbook docs?

Not sure.  @gosuri ?

**Comment by dmikey** [comment]
[akash-position.pdf](https://github.com/ovrclk/akash/files/6830738/akash-position.pdf)
