### ISSUE TITLE
Slow Downloads to Deployment (2 to 4 mb/s)

### ISSUE THREAD

**Issue by lightiv** [ovrclk/akash#1329]
### Issue type

Download to deployments incredibly slow.  2 to 4 mb/s  A PersistanceOne snapshot has been downloading for roughly 18 hours now and still going

### What happened

Downloads into the deployment are incredibly slow. 2 to 4 mb/s

### What did you expect to happen

Deployment to be much faster.  My VPS download was 280 mb/s

### How to reproduce it

Deploy an image that allows you to SSH into it and do a download.  

## Next steps

You may [join developer chat](https://akash.network/chat) for community support.

**Comment by lightiv** [comment]
I started an Omnibus install of Osmosis 12 hours agao and it is still downloading the snapshot:
```
[node1-5fd7845959-r86bd] help
[node1-5fd7845959-r86bd] {"app_message":{"auth":{"accounts":[],"params":{"max_memo_characters":"256","sig_verify_cost_ed25519":"590","sig_verify_cost_secp256k1":"1000","tx_sig_limit":"7","t>
[node1-5fd7845959-r86bd] Restoring node_key.json
[node1-5fd7845959-r86bd] Completed 227 Bytes/227 Bytes (128 Bytes/s) with 1 file(s) remaining^Mdownload: s3://osmosis-rpc02/node_key.json to root/.osmosisd/config/node_key.json.gpg
[node1-5fd7845959-r86bd] Decrypting
[node1-5fd7845959-r86bd] gpg: directory '/root/.gnupg' created
[node1-5fd7845959-r86bd] gpg: Oops: lock already held by us
[node1-5fd7845959-r86bd] gpg: keybox '/root/.gnupg/pubring.kbx' created
[node1-5fd7845959-r86bd] gpg: AES256 encrypted data
[node1-5fd7845959-r86bd] gpg: encrypted with 1 passphrase
[node1-5fd7845959-r86bd] Restoring priv_validator_key.json
[node1-5fd7845959-r86bd] Completed 345 Bytes/345 Bytes (62 Bytes/s) with 1 file(s) remaining^Mdownload: s3://osmosis-rpc02/priv_validator_key.json to root/.osmosisd/config/priv_validator_ke>
[node1-5fd7845959-r86bd] Decrypting
[node1-5fd7845959-r86bd] gpg: AES256 encrypted data
[node1-5fd7845959-r86bd] gpg: encrypted with 1 passphrase
[node1-5fd7845959-r86bd] Downloading snapshot from http://osmo-snapshot.paullovette.com/osmosis-1_2021-07-20.tar...
```

Downloading to my PC and it is only estimated to take 1 hour so while the connect is slow, twelve hours is an issue

**Comment by hydrogen18** [comment]
What URL are you downloading from and what provider are you running this on?

**Comment by hydrogen18** [comment]
Assuming you're fetching the URL in your log snippet http://osmo-snapshot.paullovette.com/osmosis-1_2021-07-20.tar  I am getting 22.0 MB/s download speed from a private host I have in an unrelated datacenter. At our SJC1 provider hosted on Equinix Metal I am seeing a download speed of no more than 6 MB/s.

It's very difficult to comment on or provide any bandwidth guarantees between our providers and a random host. We know nothing about the other end & peering changes on a realtime basis. One thing to consider is the hostname osmo-snapshot.paullovette.com appears to be using a dualstack configuration:

```
$ nslookup
> server 8.8.8.8
Default server: 8.8.8.8
Address: 8.8.8.8#53
> osmo-snapshot.paullovette.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	osmo-snapshot.paullovette.com
Address: 104.21.7.201
Name:	osmo-snapshot.paullovette.com
Address: 172.67.187.254
Name:	osmo-snapshot.paullovette.com
Address: 2606:4700:3035::6815:7c9
Name:	osmo-snapshot.paullovette.com
Address: 2606:4700:3033::ac43:bbfe
```

Within a deployment you can only access the IPv4 addresses at this time. If you conduct external tests (in a VPS or other infrastructure) please ensure you are using IPV4 only for the connection. For example with `wget` you can specify `-4` to force IPV4 only.

**Comment by lightiv** [comment]
Hi Yes, I am using Cloudflare for my domain.  I can turn of proxying and see if that help and use the -4 with wget.

**Comment by hydrogen18** [comment]
I doubt Cloudflare is the bottleneck. I was just trying to illustrate that peering over IPv6 is completely different than peering over IPv4. From within a deployment, only IPv4 is accessible.

**Comment by boz** [comment]
has this been an issue on the new clusters?

**Comment by lightiv** [comment]
Hi Adam, I am not sure if this host is part of the new cluster or not but I just tested and was getting 27 to 30 mb/s

147.75.75.107
Provider:  akash1vky0uh4wayh9npd74uqesglpaxwymynnspf6a4

**Comment by lightiv** [comment]
I think it is ok to close this as the download appears to have resolved with the new clusters.
