### ISSUE TITLE
Provider lease-status not working

### ISSUE THREAD

**Issue by Abhimanyu121** [ovrclk/akash#1332]
### Issue type

CLI command for lease status not working.

### Akash version

Built it from source with the latest commit at  ```4d41ee35bf8b73f2b5e802271c0f45a8a6762dac``` from master.
### Akash token balance

22AKT
### What happened
Running this command ```./akash provider lease-status --keyring-backend file --node http://135.181.181.122:28957 --dseq 1898288 --from akash1qphp30grcwp369uf5x5jsen56q2vtgc5l40prd --provider akash10cl5rm0cqnpj45knzakpa4cnvn5amzwp4lhcal```
is throwing ```Error: flag accessed but not defined: owner```
### What did you expect to happen
It was supposed to return lease status
### How to reproduce it

Running lease status command from CLI.

### Environment

Using Mac OS

You may [join developer chat](https://akash.network/chat) for community support.

**Comment by hydrogen18** [comment]
This is broken on master, see #1324 for updates

**Comment by Abhimanyu121** [comment]
I see thanks
