### ISSUE TITLE
Log retention: What is expected behavior?

### ISSUE THREAD

**Issue by coffeeroaster** [ovrclk/akash#1335]
If a deploy just runs a command and exits `(docker run helloworld)`, What mechanism is there to receive/view the log output?
What seems to happen is once the container exits, the log buffer is cleared and unless you get lucky and start `akash provider lease-logs` right at the right time, you will receive zero logs.

To test, create a deployment which uses the `helloworld` docker hub image. After deploying, `akash provider lease-logs` provides empty logs.  This is important for CI/CD workflows.

**Comment by dmikey** [comment]
Log buffer is removed when the deploy is torn down. Closing this ticket, because long term retention will come when storage provider implementation happens. We can't store logs, if there isn't a persistent place to put them.
