### ISSUE TITLE
[netpol] akash-deployment-restrictions prevents PODs from accessing kube-dns over 53/udp, 53/tcp in pod subnet

### ISSUE THREAD

**Issue by arno01** [ovrclk/akash#1339]
### Issue type
Bug

### Versions
Akash v0.12.1

### What happened

`akash-deployment-restrictions` Kubernetes network policy prevents PODs from accessing kube-dns over 53/udp, 53/tcp in pod subnet

### How to reproduce it
Deploy any deployment on Akash and see if it can access internal Kubernetes DNS (i.e. kube-dns) - it won't.

### Environment

Kubernetes v1.21.3
Calico v3.19.1

The Akash provider has been deployed 1:1 as in this article https://nixaid.com/deploy-akash-provider-with-kubeadm/

### Anything else we need to know?

Despite that we seem to [allow](https://github.com/ovrclk/akash/blob/7c39ea403/provider/cluster/kube/builder.go#L573) DNS to internal server (kube-dns), it gets restricted by this [policy](https://github.com/ovrclk/akash/blob/7c39ea403/provider/cluster/kube/builder.go#L591), specifically by the Except CIDR `10.0.0.0/8` as my `kube-dns` is getting IP from that range (see pod subnet right below).

My Kubernetes is set to run with these networks:

```
# cat kubeadm-config.yaml
...
networking:
  podSubnet: "10.233.64.0/18" # --pod-network-cidr, taken from kubespray
  serviceSubnet: "10.233.0.0/18" # --service-cidr, taken from kubespray
...
```

`kube-dns` is taking `10.233.0.10` IP from the service subnet:

```
# kubectl get svc --all-namespaces -o wide --show-labels |grep dns
kube-system                                     kube-dns                             ClusterIP   10.233.0.10     <none>        53/UDP,53/TCP,9153/TCP       159m   k8s-app=kube-dns                                                                                                               k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=CoreDNS
```

`kube-dns` is taking `10.233.85.131` & `10.233.85.130` IPs from the pod subnet:

```
# kubectl get pods --all-namespaces -o wide --show-labels |grep dns
kube-system                                     coredns-558bd4d5db-2shqz                    1/1     Running     0          120m   10.233.85.131    lamborghini   <none>           <none>            k8s-app=kube-dns,pod-template-hash=558bd4d5db
kube-system                                     coredns-558bd4d5db-t9r75                    1/1     Running     0          120m   10.233.85.130    lamborghini   <none>           <none>            k8s-app=kube-dns,pod-template-hash=558bd4d5db
```

Test:

```
root@lamborghini:~# kubectl exec -ti -n 38cmacar26cvskaenuv33nv1p2iad9iq7jit3ephgj16u app1-75858fc945-p8kd2  -- nslookup google.com 
```

"iptables -L -nv" point of view:

```
Chain cali-po-_PEQS7MbYv_VZ0kzwj_Z (2 references)
 pkts bytes target     prot opt in     out     source               destination         
   10   600 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:QnsDJqx8isXrAMDQ */ match-set cali40s:Ftht5x3x5WMy15Y2Nc9qjfE dst MARK or 0x10000
   10   600 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:UIC00y5hg-1FeDQ0 */ mark match 0x10000/0x10000
    0     0 MARK       udp  --  *      *       0.0.0.0/0            169.254.0.0/16       /* cali:K0CxdmTZN1u-OTzN */ multiport dports 53 MARK or 0x10000
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:sunps0Pnf8ySgrTd */ mark match 0x10000/0x10000
    1    60 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:uid_UZezSIcQX8d0 */ MARK xset 0x40000/0xc0000
    1    60 MARK       all  --  *      *       0.0.0.0/0            10.0.0.0/8           /* cali:c5fDubma52T_LQVO */ MARK and 0xfffbffff
    0     0 MARK       all  --  *      *       0.0.0.0/0            192.168.0.0/16       /* cali:G1DsvlXMZld2Mc-_ */ MARK and 0xfffbffff
    0     0 MARK       all  --  *      *       0.0.0.0/0            172.16.0.0/12        /* cali:TrR3ptaMp8Gdehqc */ MARK and 0xfffbffff
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:ZdH496bdyuOAiIqT */ mark match 0x40000/0x40000 MARK or 0x10000
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:42ojTJ8smdS-EjeA */ mark match 0x10000/0x10000
```

## Suggested changes

I suggest to allow PODs talk to the `kube-dns` by finding it directly using `namespaceSelector` & `podSelector` as follows:

### Current state

PODs can't talk to kube-dns.

- ~~Calico's ipBlock `169.254.0.0/16` doesn't play any role, unless the kube-dns pod network lies within the `169.254.0.0/16` range for some reason, which it should not. Here is more on `169.254.1.1` used by Calico https://docs.projectcalico.org/reference/faq#why-does-my-container-have-a-route-to-16925411~~
  **Update 29 July, 2021**: I've learned that `169.254.0.0/16` permits the `169.254.25.10` NodeLocal Cache DNS which kubespray installs, see [comments](https://github.com/ovrclk/akash/issues/1339#issuecomment-889293170) below for more information;
- Only 53/udp is allowed, 53/tcp is missing - not a big deal probably;
- the [next network policy rule](https://github.com/ovrclk/akash/blob/7c39ea403/provider/cluster/kube/builder.go#L598-L602) restricts all the egress POD traffic to the local CIDRs, which is good. Well, one of those (10.0.0.0/8) overlaps with the pod subnet I am using, `10.233.64.0/18`, which prevents the PODs from talking to the kube-dns POD since it’s running in a different namespace (kube-system). And the containers running within same POD are allowed to talk with each other as expected since they fall under same namespace, which gets permitted by [this rule](https://github.com/ovrclk/akash/blob/7c39ea403/provider/cluster/kube/builder.go#L562)

```
root@lamborghini:~# kubectl -n 38cmacar26cvskaenuv33nv1p2iad9iq7jit3ephgj16u get netpol akash-deployment-restrictions -o yaml
...
  - ports:
    - port: 53
      protocol: UDP
    to:
    - ipBlock:
        cidr: 169.254.0.0/16
...
...
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12
```

### Suggested change

- Allow PODs access the `kube-dns` service over 53/udp & 53/tcp within the POD subnet;

```
root@lamborghini:~# kubectl -n 38cmacar26cvskaenuv33nv1p2iad9iq7jit3ephgj16u get netpol akash-deployment-restrictions -o yaml
...
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
...
```

### iptables look after the suggested change

> I have tested this and it is working well. :-)

```
root@lamborghini:~# iptables -L cali-po-_PEQS7MbYv_VZ0kzwj_Z -nv
Chain cali-po-_PEQS7MbYv_VZ0kzwj_Z (2 references)
 pkts bytes target     prot opt in     out     source               destination         
   10   600 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:QnsDJqx8isXrAMDQ */ match-set cali40s:Ftht5x3x5WMy15Y2Nc9qjfE dst MARK or 0x10000
   10   600 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:UIC00y5hg-1FeDQ0 */ mark match 0x10000/0x10000
    1    60 MARK       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:21TSisd5filhqOOo */ match-set cali40s:TwSPtm330ezw8L_TsjzvdD8 dst multiport dports 53 MARK or 0x10000
    1    60 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:6JHuANZXMnhLhx8o */ mark match 0x10000/0x10000
    5   376 MARK       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:gS0FLa01bgq4OSpV */ match-set cali40s:TwSPtm330ezw8L_TsjzvdD8 dst multiport dports 53 MARK or 0x10000
    5   376 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:R_V0PJl1iaKYsP4H */ mark match 0x10000/0x10000
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:zMNfc9nf8SABNVa_ */ MARK xset 0x40000/0xc0000
    0     0 MARK       all  --  *      *       0.0.0.0/0            10.0.0.0/8           /* cali:9cvPZKksOczMqDSk */ MARK and 0xfffbffff
    0     0 MARK       all  --  *      *       0.0.0.0/0            192.168.0.0/16       /* cali:721FDsCZXO_HylR4 */ MARK and 0xfffbffff
    0     0 MARK       all  --  *      *       0.0.0.0/0            172.16.0.0/12        /* cali:rbUhdD78uha4jhLR */ MARK and 0xfffbffff
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:KJB0w6NtDH2MjpRU */ mark match 0x40000/0x40000 MARK or 0x10000
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:15k0ELs_Nma5sl9a */ mark match 0x10000/0x10000
```

```
root@lamborghini:~# kubectl -n 38cmacar26cvskaenuv33nv1p2iad9iq7jit3ephgj16u get netpol akash-deployment-restrictions -o yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-07-28T10:18:10Z"
  generation: 45
  labels:
    akash.network: "true"
    akash.network/namespace: 38cmacar26cvskaenuv33nv1p2iad9iq7jit3ephgj16u
  name: akash-deployment-restrictions
  namespace: 38cmacar26cvskaenuv33nv1p2iad9iq7jit3ephgj16u
  resourceVersion: "12890"
  uid: 92435312-2f7b-4691-ba3a-2c5b434f3f1a
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          akash.network/namespace: 38cmacar26cvskaenuv33nv1p2iad9iq7jit3ephgj16u
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          akash.network/namespace: 38cmacar26cvskaenuv33nv1p2iad9iq7jit3ephgj16u
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

**Comment by colinster** [comment]
This issue has been mentioned on **Akash Community**. There might be relevant details there:

https://forum.akash.network/t/containers-cant-talk-to-the-internet-as-akash-deployment-restrictions-network-policy-prevents-pods-from-accessing-kube-dns-over-53-udp-53-tcp-in-pod-subnet/654/1

**Comment by dmikey** [comment]
Will be addressed in https://github.com/ovrclk/akash/issues/1276

**Comment by coffeeroaster** [comment]
Seems like a very different issues to me. For this case, a process (i.e. curl) running in a container can not resolve IP's with DNS.

**Comment by dmikey** [comment]
> Seems like a very different issues to me. For this case, a process (i.e. curl) running in a container can not resolve IP's with DNS.

We've got networking as whole to investigate and work out. This issue isn't going to be ignored it's being collapsed.

**Comment by arno01** [comment]
> Seems like a very different issues to me. For this case, a process (i.e. curl) running in a container can not resolve IP's with DNS.

That's exactly what is causing your issue. 
Search for "nslookup" in my original post. ;)

**Comment by boz** [comment]
This is incredibly helpful.   Thanks, @arno01 !

**Comment by colinster** [comment]
This issue has been mentioned on **Akash Community**. There might be relevant details there:

https://forum.akash.network/t/containers-cant-resolve-the-ip-as-akash-deployment-restrictions-network-policy-prevents-pods-from-accessing-kube-dns-over-53-udp-53-tcp-in-pod-subnet/654/6

**Comment by colinster** [comment]
This issue has been mentioned on **Akash Community**. There might be relevant details there:

https://forum.akash.network/t/containers-cant-resolve-the-ip-as-akash-deployment-restrictions-network-policy-prevents-pods-from-accessing-kube-dns-over-53-udp-53-tcp-in-pod-subnet/654/8

**Comment by arno01** [comment]
> [copied](https://forum.akash.network/t/containers-cant-resolve-the-ip-as-akash-deployment-restrictions-network-policy-prevents-pods-from-accessing-kube-dns-over-53-udp-53-tcp-in-pod-subnet/654/8) from the Akash Community forum here for better visibility:

After testing `kubespray` deployment over 3 nodes for some time today I learned that the cross-service resolution wasn't working for me because I do not use [NodeLocal DNS Cache](https://github.com/kubernetes/enhancements/blob/b2f70d1e7/keps/sig-network/1024-nodelocal-cache-dns/README.md) which `kubespray` [employs](https://github.com/kubernetes-sigs/kubespray/blob/daed3e5b6/docs/dns-stack.md#nodelocal-dns-cache) by default (*since kubespray 2.10 release on Oct 16, 2019*) which listens over `169.254.25.10` IP by [default](https://github.com/kubernetes-sigs/kubespray/blob/0ef7af76b/roles/kubespray-defaults/defaults/main.yaml#L90) and 53/UDP requests to all addresses within `169.254.0.0/16` range are getting [permitted](https://github.com/ovrclk/akash/blob/7c39ea403/provider/cluster/kube/builder.go#L585) by the `akash-deployment-restrictions` Network Policy.

And that is not an issue with the `kubespray` deployments suggested by the [current Akash documentation](https://github.com/ovrclk/docs/blob/66308cd50/operator/provider/README.md).

So, I guess the github https://github.com/ovrclk/akash/issues/1339 issue can probably be closed, maybe with some follow-up on:

- Do we really want to allow 53/UDP requests to ALL addresses within `169.254.0.0/16`?
  I think we can still leverage `namespaceSelector` & `podSelector` as I've been suggesting in the PR in order to support `NodeLocal DNS Cache`-less deployments, such as `kube-dns (coredns)`.

**Comment by hydrogen18** [comment]
> > [copied](https://forum.akash.network/t/containers-cant-resolve-the-ip-as-akash-deployment-restrictions-network-policy-prevents-pods-from-accessing-kube-dns-over-53-udp-53-tcp-in-pod-subnet/654/8) from the Akash Community forum here for better visibility:
> 
> After testing `kubespray` deployment over 3 nodes for some time today I learned that the cross-service resolution is not working for me because I do not use [NodeLocal DNS Cache](https://github.com/kubernetes/enhancements/blob/b2f70d1e7/keps/sig-network/1024-nodelocal-cache-dns/README.md) ([doc](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/)) which `kubespray` [employs](https://github.com/kubernetes-sigs/kubespray/blob/daed3e5b6/docs/dns-stack.md#nodelocal-dns-cache) by default (_since kubespray 2.10 release on Oct 16, 2019_) which listens over `169.254.25.10` IP by [default](https://github.com/kubernetes-sigs/kubespray/blob/0ef7af76b/roles/kubespray-defaults/defaults/main.yaml#L90) and cross-service resolution is working as 53/UDP requests are permitted to all addresses within `169.254.0.0/16` range by the [`akash-deployment-restrictions`](https://github.com/ovrclk/akash/blob/7c39ea403/provider/cluster/kube/builder.go#L585) Network Policy.
> 
> And that is not an issue with the `kubespray` deployments suggested by the [current Akash documentation](https://github.com/ovrclk/docs/blob/66308cd50/operator/provider/README.md) but rather with the custom Kubernetes deployments such as [mine](https://nixaid.com/deploy-akash-provider-with-kubeadm/).
> 
> So, I guess the github #1339 issue can probably be closed, maybe with some follow-up on:
> 
> * Do we really want to allow 53/UDP requests to ALL addresses within `169.254.0.0/16`?
>   I think we can still leverage `namespaceSelector` & `podSelector` for letting `NodeLocal DNS Cache` service explicitly instead of allowing 53/UDP across `169.254.0.0/16`. As well as maybe to support `NodeLocal DNS Cache`-less deployments, such as `kube-dns (coredns)`.
> 
> **Update:**
> 
> I've updated my kubespray-less [write-up](https://nixaid.com/deploy-akash-provider-with-kubeadm/) with the **NodeLocal DNSCache** installation steps so that the cross-service DNS communication is working.
> As well as I've added few notes on how to enable the IPVS kube-proxy mode `O(1)` (instead of the iptables one `O(n)`), but, it seem to be being blocked by the "akash-deployment-restrictions" network policy currently.
> One might try the IPVS mode with his kubespray (or I will do it one day later.).

Can you show me an example of what network security policies we should consider rather than just opening up `169.254.0.0/16`? It shouldn't take long for me to try it out.

**Comment by arno01** [comment]
> > > [copied](https://forum.akash.network/t/containers-cant-resolve-the-ip-as-akash-deployment-restrictions-network-policy-prevents-pods-from-accessing-kube-dns-over-53-udp-53-tcp-in-pod-subnet/654/8) from the Akash Community forum here for better visibility:
> > 
> > 
> > After testing `kubespray` deployment over 3 nodes for some time today I learned that the cross-service resolution is not working for me because I do not use [NodeLocal DNS Cache](https://github.com/kubernetes/enhancements/blob/b2f70d1e7/keps/sig-network/1024-nodelocal-cache-dns/README.md) ([doc](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/)) which `kubespray` [employs](https://github.com/kubernetes-sigs/kubespray/blob/daed3e5b6/docs/dns-stack.md#nodelocal-dns-cache) by default (_since kubespray 2.10 release on Oct 16, 2019_) which listens over `169.254.25.10` IP by [default](https://github.com/kubernetes-sigs/kubespray/blob/0ef7af76b/roles/kubespray-defaults/defaults/main.yaml#L90) and cross-service resolution is working as 53/UDP requests are permitted to all addresses within `169.254.0.0/16` range by the [`akash-deployment-restrictions`](https://github.com/ovrclk/akash/blob/7c39ea403/provider/cluster/kube/builder.go#L585) Network Policy.
> > And that is not an issue with the `kubespray` deployments suggested by the [current Akash documentation](https://github.com/ovrclk/docs/blob/66308cd50/operator/provider/README.md) but rather with the custom Kubernetes deployments such as [mine](https://nixaid.com/deploy-akash-provider-with-kubeadm/).
> > So, I guess the github #1339 issue can probably be closed, maybe with some follow-up on:
> > 
> > * Do we really want to allow 53/UDP requests to ALL addresses within `169.254.0.0/16`?
> >   I think we can still leverage `namespaceSelector` & `podSelector` for letting `NodeLocal DNS Cache` service explicitly instead of allowing 53/UDP across `169.254.0.0/16`. As well as maybe to support `NodeLocal DNS Cache`-less deployments, such as `kube-dns (coredns)`.
> > 
> > **Update:**
> > I've updated my kubespray-less [write-up](https://nixaid.com/deploy-akash-provider-with-kubeadm/) with the **NodeLocal DNSCache** installation steps so that the cross-service DNS communication is working.
> > As well as I've added few notes on how to enable the IPVS kube-proxy mode `O(1)` (instead of the iptables one `O(n)`), but, it seem to be being blocked by the "akash-deployment-restrictions" network policy currently.
> > One might try the IPVS mode with his kubespray (or I will do it one day later.).
> 
> Can you show me an example of what network security policies we should consider rather than just opening up `169.254.0.0/16`? It shouldn't take long for me to try it out.

It's already there, check the "Suggested change" and in the first post. 😉

**Comment by arno01** [comment]
@hydrogen18 the PR is for the 

> OK got it. Merge request #1422 implements this exactly. I did a quick local test & everything is functioning as I expect. I don't really know of a way to test DNS over TCP, but if you have a suggestion I'll try it out.

that fix is in master branch, when I did `make` in the master branch, I've got `0.12.2-39-g98fd6bd9` returned by `akash version` command.
Just want to check if that's expected and whether `master` is > v0.14.1-rc6 & v0.15.x ?

**Comment by arno01** [comment]
@hydrogen18 https://github.com/ovrclk/akash/pull/1440

**Comment by boz** [comment]
Thanks @arno01 

> @hydrogen18
> 
> > OK got it. Merge request #1422 implements this exactly. I did a quick local test & everything is functioning as I expect. I don't really know of a way to test DNS over TCP, but if you have a suggestion I'll try it out.
> 
> that fix is in master branch, when I did `make` in the master branch, I've got `0.12.2-39-g98fd6bd9` returned by `akash version` command. Just want to check if that's expected and whether `master` is > v0.14.1-rc6 & v0.15.x ?

refs #1437 

 There's no need to `@` us, @arno01.  We see and pay attention to the activity feed and issues, PRs.

**Comment by hydrogen18** [comment]
As far as I know this is complete.
