### ISSUE TITLE
[docs] suggest to replace --fees with the dynamic gas adjustment

### ISSUE THREAD

**Issue by arno01** [ovrclk/akash#1404]
As more people are hitting this issue now, e.g.
``out of gas in location: WritePerByte; gasWanted: 200000, gasUsed: 202702: out of gas`` upon ``akash tx market lease create``
https://www.mintscan.io/akash/txs/DC887050EC4D4919D1C04E6DF3E2F7523EAB1FF4084698C1CD298CC62CE0FF85

I think it is a good time to replace ``--fees`` flag with ``--gas "auto" --gas-adjustment 1.15 --gas-prices "0.025uakt"``.

I've already updated all of my Akash-related docs on nixaid.com few weeks ago.

That thing goes blindly, I didn't even notice until one user told me he could not ``lease create``... neither he was sure about the cause.

**Comment by arno01** [comment]
Looks like things are running well with the dynamic fees, enabled in our helm-charts :-)
- https://github.com/ovrclk/helm-charts/pull/7
- https://github.com/ovrclk/helm-charts/pull/8

**Comment by troian** [comment]
yes, closing
