### ISSUE TITLE
Lease Billing

### ISSUE THREAD

**Issue by nalesandro** [ovrclk/akash#142]
1) Start on lease=active
2) Stop on lease=closing

**Comment by aastein** [comment]
- On lease create, check if tenant has balance >= lease price 
- process leases in market engine
 - for each active lease, send a billTenantTx

```proto
message BillTenantTx: {
  bytes deployment 
  uint64 group 
  uint64 order 
  bytes provider
}
```

- Lease app accepts and checks BillTenantTx
- Lease app subtracts lease.Price from the tenant and sends lease.Price to the provider.
