### ISSUE TITLE
Delete Deployment's Dockerimage When Lease Closes

### ISSUE THREAD

**Issue by lightiv** [ovrclk/akash#1442]
**Is your feature request related to a problem? Please describe.**

I spent several hours testing an image just to find out that the problem was not me but that the system was storing the dockerimage and not updating it for subsequent deployments.  Storing an image is typical behavior for Docker but for Akash this behavior is not good because in the case of testing, the only way you can see your changes is to change the deployment image name and edit your deployment.yml files.  Also, this behavior leaves a copy of a tennant's deployment image with a Provider they no longer have a lease with.

**Describe the solution you'd like**

Deployment (docker image) images will be delete when the lease is closed

**Describe alternatives you've considered**

See above work around for testing.  For my second point there is no work around from a user standpoint. 

**Additional context**

**Comment by boz** [comment]
To ensure you're using the right image, you can:

1. Use unique tags - a version, for instance.  This is the recommended method.
2. Use a [digest](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier).

We won't be removing docker images; this would be an unreliable way to solve the problem.   We _may_ add the ability to pull new images, but in a multi-tenant environment this may have unwanted consequences.
