### ISSUE TITLE
Unpredictable behavior when handling certificates

### ISSUE THREAD

**Issue by remeq** [ovrclk/akash#1443]
There is multiple weird/inconsistent behaviors when creating certificates. 

1. In current implementation it is not possible to have existing certificate, check its on chain status, and if present leave it be and do nothing. Current behavior is following: If certificate is present on local machine user will get message _"certificate file for address EA9522A393905F012A472B1D380EFC25DCE79BD6 already exist. check it on-chain status? [y/N]: y" if user confirms and cert is actually present on chain, the client automatically sends revoke message and that certificate gets revoked and new is created. But in fact what I want to do is: if I have a local certificate, I want to check its on-chain status and if it is present I want to keep it there. I want to revoke *any* certificate *only* if I explicitly say so. 
2. Another weird behavior is that if I say "no" to revoking message transaction, I am still presented to "creating new cert" sequence. If I confirm, I end up with two valid certs on chain. It may not necessarily be bad but it is very weird procedure to get there AKA  -> check on chain status -> reject revoke message -> confirm creating new one. This is just not very intuitive and not even clear if intended. 
3. Another weird behavior is If I say no to both revoke transaction and then the following  "creating new...." transaction, the certificate is not commited to blockchain but the client still stores (it rewrites) some newly generated cert to the local machine. So the client ends up with a cert that he thinks is valid but that cert is not present on blockchain. This is clearly wrong.
4. I believe that the checking mechanism: 
```	if yes {
		params := &types.QueryCertificatesRequest{
			Filter: types.CertificateFilter{
				Owner:  cctx.FromAddress.String(),
				Serial: x509cert.SerialNumber.String(),
			},
		}
``` 

it should should only consider valid certs. Otherwise it will be doing bad decisions about a presence of my certificate which I want to check on-chain status for.

Remek

**Comment by hydrogen18** [comment]
@remeq thanks for reporting this issue. Can you please provide steps to reproduce cases 1, 2, & 3 with the akash CLI ?

**Comment by remeq** [comment]
Ad 1)

1. Obtain a cert which is already pre-existing on the blockchain.
2. Copy the cert to following location: AKASH_HOME/<client_addr>.pem
3. Run command: akash tx cert create client --from prmclient1 --fees 5000uakt
4. For message "certificate file for address EA9522A393905F012A472B1D380EFC25DCE79BD6 already exist. check it on-chain status?" Hit yes.
5. Hit **yes** on subsequent revoking transaction request. 
6. Hit **yes** on subsequent "generating new..." transaction.
7. run akash query cert list and see that original certificate was revoked and a new one was created. 

Ad 2)

1. Obtain a cert which is already pre-existing on the blockchain.
2. Copy the cert to following location: AKASH_HOME/<client_addr>.pem
3. Run command: akash tx cert create client --from prmclient1 --fees 5000uakt
4. For message "certificate file for address EA9522A393905F012A472B1D380EFC25DCE79BD6 already exist. check it on-chain status?" Hit yes.
5. Hit **no** on subsequent revoking transaction request. 
6. Hit **yes** on subsequent "generating new..." transaction.
7. run akash query cert list and see that original certificate is still present and valid on blockchain but additional one was created. So I ended up with two valid certs on the blockchain.

Ad 2)

1. Obtain a cert which is already pre-existing on the blockchain.
2. Copy the cert to following location: AKASH_HOME/<client_addr>.pem
3. Run command: akash tx cert create client --from prmclient1 --fees 5000uakt
4. For message "certificate file for address EA9522A393905F012A472B1D380EFC25DCE79BD6 already exist. check it on-chain status?" Hit yes.
5. Hit **no** on subsequent revoking transaction request. 
6. Hit **no** on subsequent "generating new..." transaction.
7. check contents of file AKASH_HOME/<client_addr>.pem - the original was changed even though it is not commited to blockchain.

Cheers,
Premek

**Comment by remeq** [comment]
Hi, I am adding one more bad behavior caused by following code: 

https://github.com/ovrclk/akash/blob/346ef2230ca8dcff513a308816c1760c087fe5da/x/cert/client/cli/tx.go#L264

Basically it causes that if I currently have a single *and* valid cert present on blockchain, it gets revoked and new is created. from this point I have two certs on blockchain - first is with state "revoked", second is with state "valid". If I call the same cli command again, it will not revoke the valid cart (as it does during first run) because it is always checking the first which has already been revoked. So we have two different behaviors depending on how many certs I have on the blockchain.

**Comment by remeq** [comment]
> Case "Ad 1" seems to be the expected behavior?
> 

It is probably expected behavior but I think it is confusing. I think "tx create" command shouldn't have these kinds of implicit behaviors like revoking a valid cert on chain. Such intrusive operation like revoking a cert should always be explicitly asked with explicit revoke command by user. I think for clear api semantics it is always better to do simple and clear actions with particular commands.

**Comment by hydrogen18** [comment]
@remeq Yes, I agree we're looking into ways to break this into separate operations.

**Comment by hydrogen18** [comment]
@remeq you can take a look at my PR if you want to see my proposed mechanism to rework things

**Comment by remeq** [comment]
In my opinion a clean interface should facilitate two situations: 

1) User doesn't have cert
2) User brings existing cert (imagine he reinstalls his akash node but wants to reuse his cert)

So what I think is that there is one more thing that needs to be disaggregated and that is effective runtime location of cert and cert generation location.

I think that the "generate" command should only be a "utility" command and it should output the cert ideally into cwd and it shouldn't affect runtime in any way.

I think it should be explicit user action to load cert into effective runtime location (akash home). This way we will have clean interface for both user who is generating new cert as well as for user that is reusing his old one.

**Comment by hydrogen18** [comment]
If you want to load an existing certificate, all you have to do is copy the file over to the home directory.

**Comment by remeq** [comment]
Yes I know, my point was something else. A good user facing API shouldn't leave systems in undefined states after calling API or executing user facing commands. 

Now that you disaggregated cert generation and cert publishing and at the same time cert generation works with runtime location, user can run generate command which will automatically put the cert into effective runtime location and unless he also runs the publish command he will immediately start getting failed transactions because the new cert hasn't been published on blockchain. 

I think that clean solution which will minimize various pitfalls for the users is completely removing dealing with runtime effective location in all commands. This would mean that:

1) generate command would output the cert either to cwd or to a path explicitly specified by user
2) publish command would publish cert specified by a required option <filesystem_path_to_cert_location>
3) In order to affect what cert the runtime uses, user has to explicitly copy file to effective runtime location

I realize that this is in the end a nitpick and your proposed solution is already a massive improvement but still I think this would improve it even more.

**Comment by hydrogen18** [comment]
> user can run generate command which will automatically put the cert into effective runtime location and unless he also runs the publish command he will immediately start getting failed transactions because the new cert hasn't been published on blockchain.

No, this is inaccurate. The certificate is not used to sign transactions. It's used for establishing a secure connection to the provider host.

**Comment by remeq** [comment]
Right, but If I run cert generate command, then do not publish it and then will go ahead and try to execute send-manifest command, the command will fail, or am I wrong ?
