### ISSUE TITLE
Sentinel dVPN & Wireguard & Akash (Starting VPN service fails)

### ISSUE THREAD

**Issue by lightiv** [ovrclk/akash#1445]
**Is your feature request related to a problem? Please describe.**

When deploying Sentinel dVPN to Akash I receive the following error:
```
[akash14s4tlmlvy0vsps05csf8l80m7nqxmau38tehp9/3395071/1/1/akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0][web-5cc7698f6c-wxkh7] 2021-11-08T06:12:36Z INF Starting VPN service type=1
[akash14s4tlmlvy0vsps05csf8l80m7nqxmau38tehp9/3395071/1/1/akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0][web-5cc7698f6c-wxkh7] [#] ip link add wg0 type wireguard
[akash14s4tlmlvy0vsps05csf8l80m7nqxmau38tehp9/3395071/1/1/akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0][web-5cc7698f6c-wxkh7] /usr/bin/wg-quick: line 32: ip: command not found
[akash14s4tlmlvy0vsps05csf8l80m7nqxmau38tehp9/3395071/1/1/akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0][web-5cc7698f6c-wxkh7] Unable to access interface: Operation not permitted
[akash14s4tlmlvy0vsps05csf8l80m7nqxmau38tehp9/3395071/1/1/akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0][web-5cc7698f6c-wxkh7] [#] ip link delete dev wg0
[akash14s4tlmlvy0vsps05csf8l80m7nqxmau38tehp9/3395071/1/1/akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0][web-5cc7698f6c-wxkh7] /usr/bin/wg-quick: line 32: ip: command not found
[akash14s4tlmlvy0vsps05csf8l80m7nqxmau38tehp9/3395071/1/1/akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0][web-5cc7698f6c-wxkh7] Error: exit status 127
```
This is my own developed deployment.  There is no issue when deploying their non-Akash docker image to a regular server.  I assume this issue is occurring because I do not have direct access to the hardware.

**Describe the solution you'd like**

For wireguard to function with Akash.  Is there way for configuring wireguard.

**Describe alternatives you've considered**

**Additional context**

**Comment by hydrogen18** [comment]
What is a "regular server" in this context?

Akash providers are running on top of Google GVisor, which I doubt actually implements the needed interfaces for wireguard.

**Comment by lightiv** [comment]
A server from a VPS such as Digital Ocean or NetCup.

**Comment by lightiv** [comment]
I will try a non-Akash provider and see what happens

**Comment by lightiv** [comment]
I am going to close this for the reasons you state.  I tried to deploy to non-akash providers but all had various issues that prevented deployment. Hopefully in the future this will be possible. 

Summary:  this is not possible due to not having root access to the need interface.
