### ISSUE TITLE
Payment for leases with Terra stablecoins

### ISSUE THREAD

**Issue by 1MaddieX** [ovrclk/akash#1459]
**Is your feature request related to a problem? Please describe.**
Right now we pay providers in AKT, which has volatile value. Lease rates are static, so as AKT increases/decreases in value, we end up overpaying or underpaying for resources.

**Describe the solution you'd like**
[Terra](https://terra.money) recently enabled IBC, allowing stablecoins to be transferred into the rest of the Cosmos ecosystem. With this capability, Akash tenants could transfer over their local stablecoin and use it to pay for resources without having to worry about price fluctuation. Terra also has a fantastic built-in swap system, allowing any of it's stablecoins to be swapped to another, and any stablecoin can be used to pay gas. This allows providers to be currency-agnostic, making the jump to Akash even more simple and accessible.

**Describe alternatives you've considered**
There are other Cosmos-based stablecoin chains, but I haven't interacted with them so I'm not sure how easy they are to use. I've used Terra extensively and it's quite fast and intuitive.

**Comment by dmikey** [comment]
Let's discuss this at the next office hours, but over all this is a heavy decision to consider.

Accepting settlement in IBC assets has larger over all implications and considerations than enablement alone.

Closing this issue for now, as it's likely quite outside the scope of just Engineering alone.
