### ISSUE TITLE
Hostname Error: Status code was not success (500) : hostname not allowed: host <name> in use

### ISSUE THREAD

**Issue by gizmohund** [ovrclk/akash#1463]
Hi Guys,
I got an error on a a new deployment: Error while sending manifest to provider. Status code was not success (500) : hostname not allowed: host <name> in use.

I deployed a web sample with the host on an other account, closed the deployment and changed to an new account. I try to use the same manifest but I am not allowed to deploy with the hostname again. If I use an other hostname it works fine, is there a time limit or something like that? The deployment on the first account is not there any more. What can I do?

**Comment by hydrogen18** [comment]
Hi, this is probably related to the fact that not all deployments are being cleaned up at this time. This is already being addressed in the linked pull request

**Comment by gizmohund** [comment]
works fine now, thank you!!!
