### ISSUE TITLE
Connection error when querying balance

### ISSUE THREAD

**Issue by gokula-krishna-dev** [ovrclk/akash#1466]
I installed akash cli on Ubuntu and tried: `akash query bank balances <my account address>`

but I receive the following error

`Error: post failed: Post "http://localhost:26657": dial tcp 127.0.0.1:26657: connect: connection refused`

Any suggestion on what might be wrong?

**Comment by dmikey** [comment]
Please see the docs, and set up the environment, or pass the node flag. The client is trying to connect to a locally running node, which it can't find.

https://docs.akash.network
