### ISSUE TITLE
State Sync Tracking issue

### ISSUE THREAD

**Issue by faddat** [ovrclk/akash#1495]
**Is your feature request related to a problem? Please describe.**
As a relayer, I have significant difficulty with:

* disk usage
* stand up / tear down

As a validator, state sync would help me because validator nodes only need to sign the next block. 

**Describe the solution you'd like**
I'd like to be able to use state synced akash nodes with rocksdb

**Describe alternatives you've considered**
Sync from genesis with rocksdb (this doesn't seem to be possible and if you've a guide for that, please do let me know)

**Additional context**
Our relayer (till the inevitable disk failure) simultaneously reads and writes a gigabyte per second.

**Comment by boz** [comment]
State sync has been too unreliable to use with the sdk/tendermint version we have on mainnet, unfortunately.

There are a number of upstream bugfixes included in our next release, we're hoping to have more luck then.

**Comment by faddat** [comment]
It'll work with the next release :)
