### ISSUE TITLE
Feature request: provider to expose akash version via /status path

### ISSUE THREAD

**Issue by arno01** [ovrclk/akash#1502]
It would be nice to have providers tell others what akash version are they using.

```
$ curl -k https://provider.abc.com:8443/status
# would have akash version in json along the current details
```

That would help answer the following questions:
- why send-manifest fails?
- what akash version provider is running at?
- does it support persistent storage yet (v0.15.x)? etc

As well as akash client could be checking for the version during `send-manifest` (or better earlier, at lease-create maybe?) and error the user about potential incompatibility or warn him about akash versions mismatch.

Ref. https://discord.com/channels/747885925232672829/771909909335506955/934850407228911647

**Comment by boz** [comment]
Thanks @arno01 - we have added this in #1468

**Comment by baktun14** [comment]
Yes! 💯

**Comment by hydrogen18** [comment]
Closing this since the work has been done.
