### ISSUE TITLE
provider run should exit if the node is not reachable / is shut down

### ISSUE THREAD

**Issue by aastein** [ovrclk/akash#153]

**Comment by boz** [comment]
Their client interface unfortunately does not accept a `context.Context` - would be useful for doing [connection](https://golang.org/pkg/net/http/#Request.WithContext) [timeouts](https://godoc.org/golang.org/x/net/context/ctxhttp) and what not.  :crying_cat_face:

**Comment by aastein** [comment]
We could add a heartbeat event every block

**Comment by boz** [comment]
I don't even know how we can interrupt a hung connection.  It seems to just wait forever.

**Comment by aastein** [comment]
A supervising thread?

**Comment by boz** [comment]
can be solved with #196
