### ISSUE TITLE
Please backport gas=auto fix to mainnet (v0.14.x)

### ISSUE THREAD

**Issue by arno01** [ovrclk/akash#1536]
Please backport "gas=auto" fix https://github.com/ovrclk/akash/pull/1533 to the Akash mainnet (currently v0.14.x)

There is a user constantly getting "Out of gas" issue
https://discord.com/channels/747885925232672829/771909807359262751/950702310105952256

**Comment by arno01** [comment]
PR https://github.com/ovrclk/akash/pull/1537

**Comment by hydrogen18** [comment]
Closing since merged, thanks.
