### ISSUE TITLE
[VMware Tanzu K8s] kube-system ns is missing a label leading to a broken Pods 2 kube-dns communication (Documentation)

### ISSUE THREAD

**Issue by arno01** [ovrclk/akash#1546]
**Update:**
- the issue was a missing label https://github.com/ovrclk/akash/issues/1546#issuecomment-1079106742

----

Pods are allowed accessing `0.0.0.0/0` except for the private network nodes as seen here:
https://github.com/ovrclk/akash/blob/v0.14.1/provider/cluster/kube/builder.go#L609-L613

Some providers are running their nodes in the private network:
```
$ kubectl -n kube-system get pods -o wide | grep -i dns
coredns-848c5cf6b8-4t72r                                     1/1     Running   0          45d   192.168.0.5    akash-tkc01-control-plane-4smnd              <none>           <none>
coredns-848c5cf6b8-xv5fq                                     1/1     Running   0          45d   192.168.0.4    akash-tkc01-control-plane-4smnd              <none>           <none>
```

The deployment can only access the kube-dns (coredns) when the `        - 192.168.0.0/16` line is absent from the network policy:

```
$ kubectl get networkpolicy akash-deployment-restrictions -n rm38kgt61p3f27tp8kks3ldp1luq5cmtblk2npsqgfltq -o yaml 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2022-03-24T20:03:15Z"
  generation: 1
  labels:
    akash.network: "true"
    akash.network/namespace: rm38kgt61p3f27tp8kks3ldp1luq5cmtblk2npsqgfltq
  name: akash-deployment-restrictions
  namespace: rm38kgt61p3f27tp8kks3ldp1luq5cmtblk2npsqgfltq
  resourceVersion: "13423191"
  uid: 5ec965cd-817e-40c1-9ca3-e0998d57fd17
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          akash.network/namespace: rm38kgt61p3f27tp8kks3ldp1luq5cmtblk2npsqgfltq
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16   <<<<<<<<<<<<<
        - 172.16.0.0/12
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          akash.network/namespace: rm38kgt61p3f27tp8kks3ldp1luq5cmtblk2npsqgfltq
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

**Comment by arno01** [comment]
Can these ranges be removed from the `akash-deployment-restrictions` netpolicy?
And what is the intention of having them restricted?

```
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12
```

**Comment by arno01** [comment]
I guess, I'll answer myself:

The Pods should not be able to access the private network due to security, i.e. so the clients can't scan the private network and there can be more things exposed.

Still, need to figure how to make kube-dns work for the provider when he is running kube-dns in the private network.

**Comment by arno01** [comment]
This "issue" is not limited to the kube-dns only. (Going to rename it now)

This is a Pod-to-Pod communication issue when Pods are listening over private IP range.
I think this should be fixed on the K8s network layer. (i.e. by using the correct `--cluster-cidr` so Pods will listen over the correct network instead of using the private network).

Or maybe not?
I'm wondering whether this netpolicy governs the Pods layer or node layer?

**Comment by arno01** [comment]
speaking with the provider owner:
- Pod IP range is not the same as the Node range;
- nodes are allocated from following range: 192.168.2.0/24
- codedns is sitting at:  192.168.0.5

He provisions a K8s cluster in VMware tanzu, which allocates one private range for nodes and another one for internal services.

**Comment by remeq** [comment]
It would be good to understand original dev's assumptions about the way how providers allocate their Kubernetes infrastructure. I am sure that for many private datacenters will be common to allocate internal Kubernetes ranges on private IPs and only allocate public IP for _ServiceType: LoadBalancer_ services.

**Comment by arno01** [comment]
There is an interesting idea @remeq brought up, deny first and then allow.

I've already prepared the code for PR https://github.com/ovrclk/akash/compare/mainnet/main...arno01:fix-netpol-order-mainnet?expand=1 in case that works, he will test it tomorrow by manually moving these "block egress" rules before the allowing ones:


## before

* Egress rules (akash-deployment-restrictions)
  * Disable All Egress
  * Allow egress within the Tenant Namespace
  * Allow egress to 53/tcp, 53/udp for DNS
  * Allow Egress to 0.0.0.0/0
    * Block egress to 10.0.0.0/8
    * Block egress to 192.168.0.0/16
    * Block egress to 172.16.0.0/12

```
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          akash.network/namespace: rm38kgt61p3f27tp8kks3ldp1luq5cmtblk2npsqgfltq
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12
```

## after

* Egress rules (akash-deployment-restrictions)
  * Disable All Egress
  * Allow Egress to 0.0.0.0/0
    * Block egress to 10.0.0.0/8
    * Block egress to 192.168.0.0/16
    * Block egress to 172.16.0.0/12
  * Allow egress within the Tenant Namespace
  * Allow egress to 53/tcp, 53/udp for DNS

```
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12
  - to:
    - namespaceSelector:
        matchLabels:
          akash.network/namespace: rm38kgt61p3f27tp8kks3ldp1luq5cmtblk2npsqgfltq
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
```

**Comment by remeq** [comment]
So it turns out that the rules actually work as expected. The problem was that VMware Tanzu by default doesn't label kube-system namespace with appropriate metadata. After adding the kubernetes.io/metadata.name: kube-system to the namespace everything is working just fine.

**Comment by arno01** [comment]
@remeq thank you!
Before I'd close this case, I'll make sure the documentation gets updated.

VMware Tanzu K8s providers:

- kube-system namespace needs the following label:

```
kubernetes.io/metadata.name: kube-system
```

**Comment by arno01** [comment]
> Before I'd close this case, I'll make sure the documentation gets updated.

Done => https://docs.akash.network/providers/custom-kubernetes-cluster-settings/vmware-tanzu
