### ISSUE TITLE
Feature request: add KVM

### ISSUE THREAD

**Issue by figurestudios** [ovrclk/akash#1616]
**Is your feature request related to a problem? Please describe.**
Some time ago, I tried to deploy a [Golem Provider Node](https://handbook.golem.network/provider-tutorials/provider-tutorial) on Akash. Golem is another decentralized cloud computing network, similar to Akash, but without internet access for now. After going through with the installation steps, I saw that I was not able to use KVM - so the installation failed.

**Describe the solution you'd like**
andy01 on Discord mentioned that it might be possible to pass through the /dev/kvm device into the container directly.

**Additional context**
KVM makes it possible to, among other things, run:
 - [Run encrypted VMs](https://github.com/AMDESE/AMDSEV#secure-encrypted-virtualization-sev) - a way to not have to trust providers as much, where users do not have to worry about privacy regarding their deployments. While exclusive to expensive high-end CPU's, this solves the issue where users are too scared to trust Akash providers with their sensitive files.
 - [Run Golem Provider nodes](https://handbook.golem.network/provider-tutorials/provider-tutorial) - nodes that could otherwise be deployed on Akash and expand the number of deployments whenever there is demand for Golem tasks and services.
 - Simply running multiple virtual environments under one deployment

**Comment by tidrolpolelsef** [comment]
My understanding is if we passed through the KVM device, any deployment would probably be able to create basically any hardware based virtual machine or similar on the host. This would throw pricing out the window & potentially be insecure. I don't think we intend to do this at this time.

**Comment by boz** [comment]
For the time being, we are a container deployment platform.  We do intend to support VM containers like [firecracker](https://firecracker-microvm.github.io/) and [kontain](https://kontain.app/), tho.
