### ISSUE TITLE
Feature request: More flexible input for bid price scripts

### ISSUE THREAD

**Issue by figurestudios** [ovrclk/akash#1617]
**Is your feature request related to a problem? Please describe.**
When you're making pricing strategies, you have very limited information that actually goes to the bid price scripts. You see only the resources that are requested, and you must make something out of that.

**Describe the solution you'd like**
I would like for provider addresses to be included in the input that goes to the bid price scripts.

**Additional context**
This would pave the way for for example:
 - Trusted tenants - allowing traditional cloud companies to KYC users or whatever they want before letting them use their provider nodes. This would also work for companies that have servers, but have workers world-wide that must access them. Then, they can use Akash as an in-house solution with whitelisted tenant addresses.
 - Only bidding on people with X funds, X permissioned funds, X delegated funds, or X time history - as an anti-spam measure, providers could limit their bids to only people who have been using the network for a long period of time or have more than just "the tiniest amount required" in their wallet.
 - Loyal customer base - cheaper prices for people who have deployed using their provider nodes for a longer period of time 
 - Banlisting addresses - combining this with the "only bidding on X," it can help providers build out protection against spam. If someone deploys something to cancel it instantly over and over, eventually they will run out of "old" addresses, fees, or delegated funds in time for spamming the provider.
 - ,,,

**Comment by andy108369** [comment]
For the heads up:
The bid price script currently has 5 seconds execution threshold, if breached, it will error:
> `Jun 09 09:23:11 akash-provider start-provider.sh[24995]: E[2022-06-09|09:23:11.262] error calculating price                      module=bidengine-order order=akash1zh23vgfp0mjctk9pl2v6x54l49hxxt5h4skvh8/6242256/1/1 err="context deadline exceeded"`

**Comment by tidrolpolelsef** [comment]
> I would like for provider addresses to be included in the input that goes to the bid price scripts.

This would be your own provider's address in that context right? What is this for exactly?

**Comment by boz** [comment]
Thanks for the feedback; we've discussed adding more context to the pricing strategies, and this his helpful for defining that.

**Comment by figurestudios** [comment]
> This would be your own provider's address in that context right? What is this for exactly?
Sorry, meant to write tenant address. To be used for checking that tenant against a trusted list, for their "activeness," or how much funds or deployments they have, for example.

**Comment by tidrolpolelsef** [comment]
I think this is done: 

https://github.com/ovrclk/akash/blob/master/provider/bidengine/pricing.go#L407

You can check the environmental named `AKASH_OWNER` for the tenant address in bech32 format.

**Comment by figurestudios** [comment]
@tidrolpolelsef 

You're right, it is done! There was simply no mention or usage of it, so I had trouble finding it. I've got Andy to confirm, and now I have made a PR, https://github.com/ovrclk/helm-charts/pull/82, so that we may get our first example of it. Cheers
