### ISSUE TITLE
using multiple IPs on one deployment seems not to show the status

### ISSUE THREAD

**Issue by tidrolpolelsef** [ovrclk/akash#1667]
I have a deployment with multiple IPs

![Screenshot from 2022-07-15 15-21-08](https://user-images.githubusercontent.com/107218637/179305052-60c3f494-0fd5-47ac-800a-b536540a745b.png)

I can't reach those IPs, curl seems to time out. I think this is caused by Metal LB running as a NodeSet rather than a daemonset in K8S

Also the status isn't showing those IPs at all
```
$ akash provider lease-status --dseq 404 --provider akash16l4nf3z6xttgk673q536p873axmy8c7aggre3g 
{
  "services": {
    "librespeed0": {
      "name": "librespeed0",
      "available": 0,
      "total": 1,
      "uris": [
        "ggbiaa5nltdo5afnknhoi7ries.www.nocixp1.iptestnet.akashian.io"
      ],
      "observed_generation": 1,
      "replicas": 1,
      "updated_replicas": 1,
      "ready_replicas": 0,
      "available_replicas": 0
    },
    "librespeed1": {
      "name": "librespeed1",
      "available": 1,
      "total": 2,
      "uris": [
        "7qnalbfiepfij5itfoj1bt2fds.www.nocixp1.iptestnet.akashian.io"
      ],
      "observed_generation": 1,
      "replicas": 2,
      "updated_replicas": 2,
      "ready_replicas": 1,
      "available_replicas": 1
    }
  },
  "forwarded_ports": {},
  "ips": {}
}
```

**Comment by tidrolpolelsef** [comment]
well apparently this is not the problem I thought it was. Metal LB is already configured to run as a DaemonSet

https://github.com/ovrclk/akash/blob/master/_run/metallb.yaml#L324

**Comment by tidrolpolelsef** [comment]
Yeah, my understanding is that the controller should be working in concert with the speaker component to get everything working on each node. However that does not appear to the case.

**Comment by andy108369** [comment]
IIUC, it works the way where you have a set of nodes where any node could get multiple additional public IP's associated, and Metal LB does the necessary forwarding based on the public IP.

Maybe it should forward the traffic from the node that got a public IP associated _first_ to the 2nd node using the cluster virtual network (probably Calico?). Maybe the pod network gets blocked by the akash netpol rule here https://github.com/ovrclk/akash/blob/4a188686a68b3f7fbdc51b14dd8bff4b6689d94e/provider/cluster/kube/builder/netpol.go#L128-L129 ? (Just a guess)

**Comment by tidrolpolelsef** [comment]
it looks like metal LB configuration has changed quite a bit. I am going to try upgrading to the latest metal LB

**Comment by tidrolpolelsef** [comment]
All of the code changes to metal LB will make updating to the latest quite difficult at this time I feel like.

I have followed the steps to enable 'strictARP' per these instructions here under "Preparation"

https://metallb.universe.tf/installation/

What I did was ran `EDITOR=nano kubectl edit configmap -n kube-system kube-proxy` in my terminal then searched for `strictARP`.  It was false but I set it to true. It looks like things work now with IPs from the secondary node

![Screenshot from 2022-07-18 09-15-18](https://user-images.githubusercontent.com/107218637/179531765-a88d99c2-a3a1-43df-a4d0-c8743418c2f8.png)

From what I can see this causes all nodes to register the IP. It only works on the 1 that actually has the IP. Which is fine.

`akash provider lease-status` is still broken so I am investigating that now as well.

**Comment by tidrolpolelsef** [comment]
IP operator returns 204 no content in this example 

```
│ akash-provider-55f89c6dc6-zvksl:D[2022-07-18|14:54:45.343] querying for IP address status               cmp=provider lease-id=akash140rwd5t4jxfldtj3t9l0c2p0yd228ce9u7e39y/406/1/1/akash16l4nf3z6xttgk673q536p873axmy8c7aggre3g                                                                       ││ akash-provider-55f89c6dc6-zvksl:D[2022-07-18|14:54:45.343] asking for IP address status                 cmp=provider operator=ip method=GET url=http://akash-ip-operator.akash-services.svc.cluster.local.:8086//ip-lease-status/akash140rwd5t4jxfldtj3t9l0c2p0yd228ce9u7e39y/406/1/1                 ││ akash-provider-55f89c6dc6-zvksl:D[2022-07-18|14:54:45.347] ip address status request result             cmp=provider operator=ip status=204   
```

**Comment by tidrolpolelsef** [comment]
Of course, I cannot reproduce this locally

```
$ DSEQ=100 make provider-lease-status
/home/ericu/ovrclk/akash/.cache/bin/akash --home /home/ericu/ovrclk/akash/.cache/run/kube provider lease-status \
	--dseq      "100"        \
	--gseq      "1"        \
	--oseq      "1"        \
	--from      "main" \
	--provider  "akash12d67kle8dk6r54tx9fcg8gkrevz4428meets5c"
{
  "services": {
    "bew": {
      "name": "bew",
      "available": 2,
      "total": 2,
      "uris": [
        "hello1.localhost",
        "ukltabvv9hdfb3hbb7poaq089k.localhost"
      ],
      "observed_generation": 1,
      "replicas": 2,
      "updated_replicas": 2,
      "ready_replicas": 2,
      "available_replicas": 2
    },
    "web": {
      "name": "web",
      "available": 1,
      "total": 1,
      "uris": [
        "hello.localhost",
        "hhd2oo7i9h9fj81uc23duv28ng.localhost"
      ],
      "observed_generation": 1,
      "replicas": 1,
      "updated_replicas": 1,
      "ready_replicas": 1,
      "available_replicas": 1
    }
  },
  "forwarded_ports": null,
  "ips": {
    "bew": [
      {
        "Port": 80,
        "ExternalPort": 80,
        "Protocol": "TCP",
        "IP": "24.0.0.1"
      }
    ],
    "web": [
      {
        "Port": 80,
        "ExternalPort": 80,
        "Protocol": "TCP",
        "IP": "24.0.0.2"
      }
    ]
  }
}
```

:cry: Time to troubleshoot on edgenet

**Comment by tidrolpolelsef** [comment]
Doing more testing

1. Cannot reproduce the problem running everything local with `_run/kube` example
2. I can reproduce the problem locally with the `_run/single` example

So I thought this was a permissions problem, something with how I had setup roles in K8S. I installed kubectl in the pod container and :shrug: it just works 

```
root@akash-ip-operator-86f54856f7-jlcfn:/# ./kubectl get -n sl3m2n61a3uaaaj0dl7c1pook5lqdp7bc0dhjafdk80a4 service -l 'akash.network=true,akash.network/service-target=metal-lb'
NAME            TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
bew-ip-80-tcp   LoadBalancer   10.96.34.251   24.0.0.1      80:31800/TCP   39m
web-ip-80-tcp   LoadBalancer   10.96.23.182   24.0.0.2      80:31540/TCP   39m
```

So it isn't a permissions issue

**Comment by tidrolpolelsef** [comment]
OK, this has nothing to do with K8S permissions or even K8S really.

Alright well in past discussions we decided that provider address was a configurable value on the IP address operator. If you configure **that wrong** you get no information back on the endpoint for IPs in use. After I fixed that, the status shows up

```
$ akash provider lease-status --dseq 406 --from deploy0 --provider akash16l4nf3z6xttgk673q536p873axmy8c7aggre3g 
{
  "services": {
    "librespeed0": {
      "name": "librespeed0",
      "available": 1,
      "total": 1,
      "uris": [
        "smrm2o5uc1dt37kfm6ffpt40u8.www.nocixp1.iptestnet.akashian.io"
      ],
      "observed_generation": 1,
      "replicas": 1,
      "updated_replicas": 1,
      "ready_replicas": 1,
      "available_replicas": 1
    },
    "librespeed1": {
      "name": "librespeed1",
      "available": 2,
      "total": 2,
      "uris": [
        "l4hkr6n1btehn33vfa8a1vvuoo.www.nocixp1.iptestnet.akashian.io"
      ],
      "observed_generation": 1,
      "replicas": 2,
      "updated_replicas": 2,
      "ready_replicas": 2,
      "available_replicas": 2
    }
  },
  "forwarded_ports": {},
  "ips": {
    "librespeed0": [
      {
        "Port": 80,
        "ExternalPort": 80,
        "Protocol": "TCP",
        "IP": "198.204.231.227"
      }
    ],
    "librespeed1": [
      {
        "Port": 80,
        "ExternalPort": 80,
        "Protocol": "TCP",
        "IP": "198.204.231.228"
      }
    ]
  }
}
```

So everything is working as intended. I just need to configure stuff correctly.

**Comment by andy108369** [comment]
> Alright well in past discussions we decided that provider address was a configurable value on the IP address operator. If you configure **that wrong** you get no information back on the endpoint for IPs in use. After I fixed that, the status shows up

Thank you, Sir.

Whoever gets to this issue for any reason, the issue arise when `ip-operator` runs with a wrong `provider` address, e.g. they should match as in this **good** example:

```
$ kubectl -n akash-services get deployment akash-provider -o yaml | grep -A1 AKASH_FROM | tail -2
        - name: AKASH_FROM
          value: akash1puknctju6re3vcfpund9ry37xcun5ul8x4pvy2
$ kubectl -n akash-services get deployment akash-ip-operator -o yaml | grep -A1 -B3 -- '\-\-provider' | tail -5
      - args:
        - provider-services
        - ip-operator
        - --provider
        - akash1puknctju6re3vcfpund9ry37xcun5ul8x4pvy2
```

If not, you are going to get these kind of errors:

- `ip-operator`: `no IP address to status for lease         operator=ip lease-id=...`
- `provider`: `ip address status request result             cmp=provider operator=ip status=204`
