### ISSUE TITLE
Some steps missing in doc <Dev Environment: "Single" configuration>

### ISSUE THREAD

**Issue by ayoucai** [ovrclk/akash#1684]
**Is your feature request related to a problem? Please describe.**
I try to do some experiments under the guidance of doc <Dev Environment: "Single" configuration> (https://github.com/ovrclk/akash/tree/master/_run/single). An error occured when i try 
ro 'Run local network'  (using command 'make kustomize-install-node'),  error as belows:
![image](https://user-images.githubusercontent.com/5180421/184595083-2c4cf8e0-458e-4646-af49-ff0d8a2d7925.png)

**Describe the solution you'd like**
update the instructions.

**Describe alternatives you've considered**
It seems 'docker-image.yaml' was not generated successfully. I checked Makefiles and found below command can create 'docker-image.yaml':
  DOCKER_IMAGE=kubeedge/edge-app-1:v1.0.0  make  kind-configure-image
But error still occured when 'Run local network',  error as belows:
![image](https://user-images.githubusercontent.com/5180421/184596155-198c6d31-a304-4d85-802b-f229c9fe7816.png)

**Additional context**

**Comment by troian** [comment]
won't fix. `_run` examples moved to the [provider-services](https://github.com/ovrclk/provider-services)
