### ISSUE TITLE
add proposer to app context

### ISSUE THREAD

**Issue by aastein** [ovrclk/akash#169]
To validate market transactions the apps need to know the facilitator for a given block.

**Comment by boz** [comment]
See comment [here](https://github.com/ovrclk/akash/issues/170#issuecomment-378122214)

**Comment by nalesandro** [comment]
Open issue in tendermint

**Comment by aastein** [comment]
https://github.com/tendermint/tendermint/issues/1472

**Comment by aastein** [comment]
The Terdermint team will be addressing this: soon.https://github.com/tendermint/tendermint/issues/1472#issuecomment-381941146
Will close this issue once our code base has it.

**Comment by gosuri** [comment]
Fixed in upstream tendermint/tendermint#1134

Need confirmation from @boz
