### ISSUE TITLE
add validator without restart

### ISSUE THREAD

**Issue by aastein** [ovrclk/akash#170]
add a validator node without restart in EndBlock

http://tendermint.readthedocs.io/projects/tools/en/master/app-development.html#endblock

**Comment by boz** [comment]
I couldn't figure out how to get the validator set in the apps - the block only has a compressed representation of it.

If we _can_ get the validator set for each block, then we can validate facilitator transactions without adding the block creator to the block header.

**Comment by aastein** [comment]
@boz How will getting the validator set for the block allow us to validate the facilitator tx's? How will that list determine the proposer for the accepted block?

**Comment by boz** [comment]
With the validator set and round number you can determine the proposer.  There is a `ValidatorSet` or some such that does the determination in the tendermint code.

**Comment by aastein** [comment]
Do we already have the round number for a previous block?

**Comment by boz** [comment]
Each block goes through round (r) 0 through R  The validators are sorted and the rth entry is used as the proposer.  The proposer on the first round is the actual block creator.  I believe that we are only triggering facilitator actions for the first round, but I may be wrong.

If the block simply included the address of the block creator, it'd simplify a lot of things.

**Comment by gosuri** [comment]
Fixed in upstream tendermint/tendermint#1134

Please verify @boz

**Comment by jackzampolin** [comment]
I think moving to the SDK should close this issue.
