### ISSUE TITLE
Node upgrade error

### ISSUE THREAD

**Issue by COLUD4** [ovrclk/akash#1717]
panic: cannot delete latest saved version (211)

The node upgrade to 1.8.0 reported an error, and the node was started using a snapshot, with the same error that

**Comment by airstring** [comment]
@COLUD4  I've taken care of it.I use v0.18.1 and then download the latest snapshot:https://snapshots.stake2.me/akash/

**Comment by troian** [comment]
need to set `pruning=nothing`
more details available in [mainnet4-upgrade-docs](https://github.com/ovrclk/docs/blob/master/mainnet4-upgrade-docs/akash-mainnet4-node-upgrade-guide.md)
