### ISSUE TITLE
Investigate perf issue

### ISSUE THREAD

**Issue by nalesandro** [ovrclk/akash#182]
Aaron knows whats up ofc

**Comment by aastein** [comment]
The issue is due to tendering voting system and is partially expected. More voting nodes -> more votes to send -> more votes to wait for -> more votes to count.

**Comment by boz** [comment]
We're going to need to address this eventually if 100 nodes is going to push our block time from 3 seconds to 10 seconds.

**Comment by nalesandro** [comment]
Maybe get rid of 1 sec wait
