### ISSUE TITLE
txutil.Client: handle stale nonces

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#200]
Long-running processes that send transactions may have their internal nonce accounting fall behind the actual nonce, especially if it is sending transactions concurrently.

One way to handle this might be to catch stale nonce errors and retry with a freshly-calculated nonce.

Another way might be to watch for all transactions from the sender and keep the nonce up to date accordingly.

**Comment by gosuri** [comment]
@boz: moving to stale status and will reopen if this is still an issue
