### ISSUE TITLE
integration: automate kubernetes deployments testing

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#234]
Add an integration suite which runs workloads on a kube-backed provider.

* Create/Close deployment.
* Make sure tokens are transferred during lease.

**Comment by gosuri** [comment]
This will improve dev productivity in amazing ways

**Comment by boz** [comment]
Yeah would really, really like to have this.

Too a stab at it at one point but didn't have time to finish it.

**Comment by gosuri** [comment]
no worries, i prioritized items here https://github.com/orgs/ovrclk/projects/2
