### ISSUE TITLE
kube: add controller for handling CRD manifests to enable deployment updates

### ISSUE THREAD

**Issue by aastein** [ovrclk/akash#262]
in order to update deployments based on manifest CRD, the manifest CRD also needs a controller which dictates what kube objects and configuration the manifest represent.

**Comment by gosuri** [comment]
We are able to update deployments, I believe this is no longer needed

**Comment by boz** [comment]
This was related to a necessary implementation improvement which is to split the provider functionality up into a number of independent k8s operators/controllers.

The use-case described here doesn't quite capture it tho.  Will close for now and create a more thorough design proposal shortly.

**Comment by gosuri** [comment]
🔥🚀🌚
-- 
sent on mobile
