### ISSUE TITLE
Limit CPU usage per deployment

### ISSUE THREAD

**Issue by aastein** [ovrclk/akash#291]
do the limiting when the provider bids on an order. Don't bid on orders that take up too much stuff.

**Comment by boz** [comment]
Per manifest group?  What's the use case for this?  We're doing it per service replica now.

**Comment by aastein** [comment]
These set of issues were notes Nick made that I converted to issues. I think it this one is for limiting the resources a demo user can take up in a single provider.

**Comment by nalesandro** [comment]
The group hath decided to limit to a max of 1CPU for all services per order
