### ISSUE TITLE
Akash client defaults to testnet

### ISSUE THREAD

**Issue by nalesandro** [ovrclk/akash#320]

**Comment by boz** [comment]
@gosuri what `host:port` should it connect to?  Thinking of adding a `-X package.var=host:port` for it [in the release config](https://github.com/ovrclk/akash/blob/5003574996ad1cc58e90cd23909ff1e308153e5b/.goreleaser.yml#L8)

**Comment by gosuri** [comment]
@boz use `akashtest.net:80`, will add the DNS shortly
