### ISSUE TITLE
accounts: support user-supplied password during key generation

### ISSUE THREAD

**Issue by gosuri** [ovrclk/akash#403]
Currently, all keys share a static password. A user-specified password enhances security.

**Interactive Workflow** 

```
akash key create <name> 

Specify a password for you key:
Confirm password:
```

**Disable confirmation for non interactive**

```
akash key create <name> --password <pass> --no-confirm --mode (json|shell)
```

**Comment by gosuri** [comment]
Is this still valid @boz with SDK migration?

**Comment by boz** [comment]
Yeah - default passwords are used at the moment; there is no user input.
