### ISSUE TITLE
client: implement query functionality for REST and CLI interfaces

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#442]
Implement REST and CLI interfaces for singular and collection objects:

- [ ] Deployment
- [ ] Order
- [ ] Bid
- [ ] Lease
- [ ] Provider

#### Singular vs Collection

The default mechanism is `akash query provider provider` for singular and  `akash query provider providers` for collection. Ideally, a single command should handle both type of objects. 

For example: `akash query providers <provider>..` should present a single or multiple records

#### Remote filtering

Currently, the filtering happens on the client. Ideally, the filtering should happen on the server for optimal user experience.

**Comment by jackzampolin** [comment]
Will take this.

**Comment by akhilkumarpilli** [comment]
@gosuri check this https://github.com/ovrclk/akash/commit/104608644947bcaf3c495b197851fc1d8199778b. We used `codec.MarshalJSONIndent` instead of `sdkutil.RenderQueryResponse` to get query response and it worked. Do we specifically need to use `sdkutil` or is it fine to use `codec`?

**Comment by akhilkumarpilli** [comment]
Also for providers, we don't have any provider id for now. To query single provider, should we use host and owner?

**Comment by gosuri** [comment]
> @gosuri check this [1046086](https://github.com/ovrclk/akash/commit/104608644947bcaf3c495b197851fc1d8199778b). We used `codec.MarshalJSONIndent` instead of `sdkutil.RenderQueryResponse` to get query response and it worked. Do we specifically need to use `sdkutil` or is it fine to use `codec`?

@boz can help you with that

**Comment by akhilkumarpilli** [comment]
> every provider has a public key

I created provider with host, region and moniker values. But when I tried to query all providers list, I got this output:
```
[
  {
    "owner": "akash1kzpa4zlvxyqlz4kqe0rneap3l5c9r2x3u3cse0",
    "host-uri": "http://akash.sahithnarahari.com",
    "attributes": [
      {
        "key": "cmVnaW9u",
        "value": "c2Zv"
      },
      {
        "key": "bW9uaWtlcg==",
        "value": "YWtoaWw="
      }
    ]
  }
]
```
In above provider details, I can't find any public key for provider.

**Comment by anilCSE** [comment]
Yes, there's no pubkey in the output. Can you dig into the code and try to add a pubkey to the response? Btw, @gosuri we cannot read plain private key of an account now, do you suggest any other method to create provider private key? previous docs ref: https://docs.akash.network/providers/kube#deploy-akash-provider-service-on-kubernetes

**Comment by boz** [comment]
Sorry, I'm just seeing this now.

The provider address is it's owner's address; you can use the account owner's keys.

I added the single provider query in #453 

`sdkutil.RenderQueryResponse` is a small wrapper around `codec.MarshalJSONIndent` to reduce repetition across all of the query handlers.  Please continue to use it or remove it from everywhere if there's a good reason to.

Thanks for looking into this!

**Comment by boz** [comment]
note that #440 should be done prior to this for the REST endpoints.

**Comment by akhilkumarpilli** [comment]
> Implement REST and CLI interfaces for singular and collection objects:
> 
>     * [ ]  Deployment
> 
>     * [ ]  Order
> 
>     * [ ]  Bid
> 
>     * [ ]  Lease
> 
>     * [ ]  Provider
> 
> 
> ### Notes:
> #### Singular vs Collection
> 
> The default mechanism is `akash query provider provider` for singular and `akash query provider providers` for collection. Ideally, a single command should handle both type of objects.
> 
> For example: `akash query providers <provider>..` should present a single or multiple records
> #### Remote filtering
> 
> Currently, the filtering happens on the client. Ideally, the filtering should happen on the server for optimal user experience.

There occurs a problem if we change provider query to `akash query providers <provider>` where provider is optional. By this, we can have only this command in provider module. We cannot add further any query commands to provider module if required.

**Comment by boz** [comment]
Good point. I forget - does cobra allow default commands?  Alternatively, how about something like this:


|type|command|notes|
|---|---|---|
|collection|`provider list`|
|singular|`provider get [address]`| address defaults to current key address if `--from` is given|

**Comment by akhilkumarpilli** [comment]
> Good point. I forget - does cobra allow default commands? Alternatively, how about something like this:
> type 	command 	notes
> collection 	`provider list` 	
> singular 	`provider get [address]` 	address defaults to current key address if `--from` is given

Looks good. We can update to this.

**Comment by akhilkumarpilli** [comment]
> Good point. I forget - does cobra allow default commands? Alternatively, how about something like this:
> type 	command 	notes
> collection 	`provider list` 	
> singular 	`provider get [address]` 	address defaults to current key address if `--from` is given

We cannot use --from flag in queries as it is to specify key used for signing. Instead we can go with arguments as per cosmos structure. provider get <address> command without --from flag is good for singular type.

**Comment by anilCSE** [comment]
Yes, I think SDK registered this flag for txs and there would be conflict if we re-use them for queries. Instead we can use `owner` flag but that doesn't fit best. It's better if we keep all the required params in the query cmd and avoid flags. We can use flags for optional params may be.
`... provider get <address>` looks like a better convesion without making the `address` param optional

Also, what if there are more than one providers registered from single address? Are we restricting this in create provider @akhilkumarpilli ?

**Comment by akhilkumarpilli** [comment]
Yeah, we are restricting in create provider. Only one provider can be created per single address.

**Comment by boz** [comment]
There are some existing utilities for getting IDs for the `get` commands, and I believe that they can be used for filtering as well.

There are two components of each: one for adding flags to the command, one for parsing them when executing the command.

|object|add flag|parse flag|
|---|---|---|
|`DeploymentID`|[`AddDeploymentIDFlags`](https://github.com/ovrclk/akash/blob/9161a1abe6bf21223ced0b81a2f5167a02d012e2/x/deployment/client/cli/flags.go#L10-L13)|[`DeploymentIDFromFlags`](https://github.com/ovrclk/akash/blob/9161a1abe6bf21223ced0b81a2f5167a02d012e2/x/deployment/client/cli/flags.go#L16-L33)|
|`GroupID`|[`AddGroupIDFlags`](https://github.com/ovrclk/akash/blob/9161a1abe6bf21223ced0b81a2f5167a02d012e2/x/deployment/client/cli/flags.go#L36-L39)|[`GroupIDFromFlags`](https://github.com/ovrclk/akash/blob/9161a1abe6bf21223ced0b81a2f5167a02d012e2/x/deployment/client/cli/flags.go#L42-L54)|

The pattern continues for `OrderID` and `BidID` in [`x/market`](https://github.com/ovrclk/akash/blob/9161a1abe6bf21223ced0b81a2f5167a02d012e2/x/market/client/cli/flags.go).

The original idea was that if for `get` commands you would have to supply all of the options, for `list` commands the populated flags would be used for filtering the results.
