### ISSUE TITLE
use 'akt' as denomination instead of default 'stake'

### ISSUE THREAD

**Issue by gosuri** [ovrclk/akash#448]
The genesis file,  `staking.params.bond_denom` should be 'akt'. 

See https://docs.akash.network/v/testnet2/testnet-2/testnet2#attach-genesis-account

```json
    "staking": {
      "params": {
        "unbonding_time": "1814400000000000",
        "max_validators": 100,
        "max_entries": 7,
        "historical_entries": 0,
        "bond_denom": "stake"
      },
      "last_total_power": "0",
      "last_validator_powers": null,
      "validators": null,
      "delegations": null,
      "unbonding_delegations": null,
      "redelegations": null,
      "exported": false
    },
```

**Comment by anilCSE** [comment]
I think this should be handled via changes in genesis file directly. It doesn't look like a straight forward change in `app.go`, for sdk `params`.

**Comment by boz** [comment]
Done by @anilCSE via editing the genesis file.
