### ISSUE TITLE
Refactor akash modules to recommended structure

### ISSUE THREAD

**Issue by fedekunze** [ovrclk/akash#465]
**Is your feature request related to a problem? Please describe.**

Standardization of Cosmos SDK modules code. Higher learning curve for SDK developers. Possible bugs because of code mismatch. 

**Describe the solution you'd like**

Update the Akash modules to match the recommended [module structure](https://docs.cosmos.network/master/building-modules/structure.html) from the Cosmos documentation.

**Describe alternatives you've considered**

The alternative is to leave the modules as is. Cons are described in the first section. No pros.

**Additional context**

**Comment by boz** [comment]
I have tried to follow it where it makes sense to.

I think that `cosmos-sdk` code tends to not have a great module design, a couple symptoms of this:

* everything is exported.
* `exported.go` is basically a giant hack.
* no code or constant re-use between `x/client/cli`, `x/client/rest`, and the querier.
* `query` is coupled with `keeper`
* use of exported `vars` doesn't adequately protect data.

And so on.

Also, the standard module structure seems to change a lot.

All that being said, I'm open to considering specific changes, particularly if they're coupled with functional improvements.

**Comment by boz** [comment]
This ticket is very broad and includes changes that we won't be adopting.

I'd be happy to consider more specific proposals related to this general theme, tho.
