### ISSUE TITLE
provider cluster: kubernetes CRDs

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#481]
* Update the CRD [types](https://github.com/ovrclk/akash/blob/0bfe385b1f20dcebf489f4759942d36611c78a9a/pkg/apis/akash.network/v1/types.go) so that they're compatible with our new type design.
* [re-generate](https://github.com/ovrclk/akash/blob/0bfe385b1f20dcebf489f4759942d36611c78a9a/Makefile#L102-L105) the [CRD clients](https://github.com/ovrclk/akash/tree/0bfe385b1f20dcebf489f4759942d36611c78a9a/pkg/client).

**Comment by Ropes** [comment]
Using a checkout of k8s.io/code-generator:v0.18.2, I've been able to generate all the `akash` clientset and integration packages. `akash` and `akashd` build fine, so now we primarily need to sort out our k8s dependency woes. There are some vscode flagged error messages which I'm a little confused by, but they might be vscode being confused.

I still need to go back and update the CRD types, but now I have a path see results of a build.

**Comment by hydrogen18** [comment]
I think this can be considered done?
