### ISSUE TITLE
akash client: provider REST client

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#482]
Show results from the endpoints defined in #480

**Comment by akhilkumarpilli** [comment]
@boz We tried to setup kubernetes cluster using disco and with latest akash version i.e., with cosmos sdk integrated. We are unable to get private key using latest akash. However we tried different ways and deployed it. /status endpoint is giving us "Service Unavailable". I think, we need to solve it before working on this issue.

**Comment by boz** [comment]
okay thanks.  sounds like a deployment issue, I believe @gosuri is working on that.
