### ISSUE TITLE
buildkite: out of memory

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#494]
buildkite builds are running out of memory

**Comment by Ropes** [comment]
Alright we're back up and running with RunKite t2.micro instances. Now that I understand the CloudFormation stack better; if we need to increase instance size further it won't be such an issue.

**Comment by Ropes** [comment]
Memory constraints fixed, BuildKite servers now run with t2.micro. I now know how to upsize if we need to in the future as well. https://github.com/ovrclk/akash/pull/496 fixes our BuildKite tests and will get `master` back to :green_circle:.
