### ISSUE TITLE
docs: introduce conventional commits

### ISSUE THREAD

**Issue by troian** [ovrclk/akash#516]
The Conventional Commits specification is a lightweight convention on top of commit messages. It provides an easy set of rules for creating an explicit commit history; which makes it easier to write automated tools on top of. This convention dovetails with SemVer, by describing the features, fixes, and breaking changes made in commit messages.

More details in the [spec](https://www.conventionalcommits.org/en/v1.0.0)

**Comment by gosuri** [comment]
👍

**Comment by boz** [comment]
@troian can this be closed?
