### ISSUE TITLE
lint: fix gofmt

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#542]
* Fix `gofmt` warnings from the [lint checker](https://github.com/ovrclk/akash/blob/master/.github/workflows/tests.yml#L39) step for it.
 * Remove `continue-on-error: true` from `lint gofmt` step.

**Comment by troian** [comment]
@boz it would make sense to use `goimports` as it does all `gofmt` plus pretties the go imports

**Comment by boz** [comment]
@troian this is using `golangci-lint` which aggregates a lot of linters.  I split out tasks for many of them that are warning now.  `goimports` may be being used already but is not a problem yet.
