### ISSUE TITLE
lint: fix gochecknoglobals

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#545]
* Fix `gochecknoglobals` warnings from the [lint checker](https://github.com/ovrclk/akash/blob/master/.github/workflows/tests.yml#L39) step for it.
 * Remove `continue-on-error: true` from `lint gochecknoglobals` step.

**Comment by akhilkumarpilli** [comment]
@boz, We cannot avoid global variables of [this](https://github.com/ovrclk/akash/blob/master/x/deployment/types/codec.go#L7) type. I cannot find a way to solve this. And almost all the warnings from `gochecknoglobals` linter are of same type. So, I think it's better to not implement `gochecknoglobals` linter.

**Comment by boz** [comment]
@akhilkumarpilli no problem.  you can disable it for just those cases with something like

```go
var cdc = codec.New() // nolint: gochecknoglobals
```

or something like that.

**Comment by boz** [comment]
We've decided to not use this linter - it's too intrusive.
