### ISSUE TITLE
deployment version

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#565]
A deployment has two components: the on-chain resource model used for the auction, and the off-chain description of _what_ is to be deployed called the _manifest_.

The manifest is sent to providers, and providers need a way to verify that the manifest they sent.

The "deployment version" is a hash of the manifest and resides in the on-chain `deployment.Version`.

* [x] `x/deployment/types`: require version in `MsgCreate`.
* [x] `x/deployment/client/cli`: calculate deployment version and include in `MsgCreate`.
* [x] `x/deployment/handler`: consume version from `MsgCreate`.

To do this correctly we need to have a stable serialization of the manifest.  This means sorting all components consistently.  This is currently done in `sdl/v1.go` when parsing an sdl file; we should probably move that functionality to an isolated package to be used elsewhere.

**Comment by Ropes** [comment]
Version/Hashing of the SDL sorted though somewhat inefficient, it's not in a critical compute bottleneck path.

**Comment by Ropes** [comment]
Unit tests showing functional passing of Version from Create to Update messages *in keepers*. Still plumbing the `akashctl` commands.

Some was referencing the `Version` field type as an sdk.AccAddress. From reading some commented code, seems like there was an initial idea to integrate the owner address into the version, but this implementation just uses the sha256 of the SDL struct.
