### ISSUE TITLE
design: overlay network

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#6]
Bare-bones overlay network design, documented in `_docs/`.

1. Given a manifest, determine all (service,peer) pairs needing a secure connection.
1. Negotiate secure connection with peer for each pair.
1. Teardown connections when lease is no longer active.

Note: do not handle manifest updates.

 * [ ] Determine necessary connections for given manifest distribution.
 * [ ] Monitor for when a peer connection is no longer needed (peer lease inactive).
 * [ ] Certificate design
   * [ ] Ephemeral leaf certs for each connection.
   * [ ] On-chain root cert for each datacenter.
 * [ ] Network Protocol
   * [ ] Open connection to peer (and vice-versa).
   * [ ] State machine for each connection.
     * [ ] Illustrated with [graphviz](https://graphviz.org).
   * [ ] Messages/service declared in [gRPC](https://grpc.io) file.
 * [ ] Illustrate with [mermaid](https://mermaidjs.github.io/)

**Comment by gosuri** [comment]
moved to _docs/tasks.md
