### ISSUE TITLE
account sequence handling in long-lived processes

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#605]
The bid engine [submits messages to the chain](https://github.com/ovrclk/akash/blob/082cb048d367cadebc16de5efb592622f0de2700/provider/bidengine/order.go#L187-L191) using an [sdk utility](https://github.com/ovrclk/akash/blob/082cb048d367cadebc16de5efb592622f0de2700/client/client.go#L81-L84) that looks up the account's sequence number when signing the transaction.

There are all kinds of race conditions with this:

* what if the provider is bidding on two leases at once?
* what if two bids are sequential but end up in the same block?
* etc...

We need a way to gracefully handle concurrent transaction submissions.  We have [previously](https://github.com/ovrclk/akash/blob/stable/txutil/client.go#L79-L87) used a simple counter, but this runs into problems when the provider account is submitting transactions through any other means (operator cancelling leases through the CLI, for instance).

edit: solution suggested by @jackzampolin is to simply [retry](https://github.com/avast/retry-go) events.

**Comment by jackzampolin** [comment]
I know the microtick team has done a bunch of work here too. We could setup some time to sync with them https://gitlab.com/microtick/mtapi

**Comment by boz** [comment]
https://github.com/cosmos/cosmos-sdk/issues/5595

**Comment by boz** [comment]
I spoke with @anilCSE and it sounds like the best thing to do here is to increment the sequence number ourselves.

General direction for a quick fix would then be:

Create an alternate implementation of the [`TxClient`](https://github.com/ovrclk/akash/blob/9c9377e21089fbc8162729edd3dea133ee046a03/client/client.go#L40-L43) interface that

1. uses a single thread for broadcasting transactions
1. has a queue of transactions that are waiting to be sent.
1. uses [`tx.PrepareFactory`](https://github.com/ovrclk/akash/blob/9c9377e21089fbc8162729edd3dea133ee046a03/client/client.go#L84) to initially populate a factory with the account number and sequence number
1. thereafter increments the sequence number after every send with `SetSequence()`.
1. Possibly occasionally re-fetching the account sequence number from the chain in case things are out of sync.
