### ISSUE TITLE
events: replace event type

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#607]
We are currently emitting evens with type of [`sdk.EventTypeMessage`](https://github.com/ovrclk/akash/blob/082cb048d367cadebc16de5efb592622f0de2700/x/deployment/types/event.go#L26).

These appear to be use for actual transaction messages.  It looks like other projects use their own name for the type; we should too.  `akash` might be a reasonable name for our message types, not sure.

All of the generated events in `x/*/types/event.go` would need to be modified as well as the processing that's done in [`sdkutil`](https://github.com/ovrclk/akash/blob/082cb048d367cadebc16de5efb592622f0de2700/sdkutil/event.go#L30)

**Comment by Ropes** [comment]
What domain should this string be changed to? 

Some ideas:
* `akash`
* `akashnetwork`
* `aka` - double duty being short and Japanese for 'red'.

**Comment by boz** [comment]
I think just `akash` or `akash.network` or `akash.v1` or something.  probably just `akash` is good lol.
