### ISSUE TITLE
chore: standardize on `.yaml`

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#630]
Only because there are already more `.yaml` files.

```sh
$ git ls-files '*.yaml' | wc -l
30
$ git ls-files '*.yml' | wc -l
24
```

* [ ] replace all `.yml` suffixes with `.yaml`
* [ ] write a github action to ensure that no `.yml` files are added.

_**NOTE:** I actually prefer `.yml`, so if there are arguments for using that instead, I'm all ears_

**Comment by troian** [comment]
Official doc `please use **yaml**` but I prefer too in use `yml`
