### ISSUE TITLE
perf: Bid querying uses prefix 

### ISSUE THREAD

**Issue by Ropes** [ovrclk/akash#637]
Improve the search performance of querying for Bids. 

Function to update: https://github.com/ovrclk/akash/blob/master/x/market/keeper/keeper.go#L343-L349

Potential implementation:
```
		store := ctx.KVStore(k.skey)
		iter := sdk.KVStorePrefixIterator(store, orderPrefix)
		for ; iter.Valid(); iter.Next() {
			var val types.Order
			k.cdc.MustUnmarshalBinaryBare(iter.Value(), &val)
			if stop := fn(val); stop {
				break
			}
		}
```

Needs additional filtering to match the Order being matched though.

**Comment by akhilkumarpilli** [comment]
Sorry, I didn't get this, Currently, what we implemented is using prefix right? `k.WithBids` is a function which uses prefix search.

**Comment by boz** [comment]
Indexes for bids are `(tenant-id,dseq,gseq,oseq,provider-id)` - `WithBidsForOrder()` can do a range on `(tenant-id,dseq,gseq,oseq)`.
