### ISSUE TITLE
mainnet branch: possible to do with build tags?

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#683]
I think we may be able to forgo the headache of a "mainnet" branch by using build tags - split mainnet-speciality into a separate file.

rough illustration:

`app/app_configure_mainnet.go`:
```go
// +build mainnet

func addAkashModules(...) {
  // probably skip things
}
```

`app/app_configure.go`:
```go
// +build !mainnet

func addAkashModules(...) {
  // add our modules
}
```

**Comment by boz** [comment]
refs #563

**Comment by gosuri** [comment]
That’ll be fantastic not to have to maintain divergent branches, cosmos gaia has this for ledger etc — @jackzampolin?

**Comment by boz** [comment]
@akhilkumarpilli let's give this a try if you have time.  we'd probably want to run tests in both modes.  we can build the correct binary based off of the tag name, don't worry about that for now - just build as normal for now.

**Comment by anilCSE** [comment]
> That’ll be fantastic not to have to maintain divergent branches, cosmos gaia has this for ledger etc — @jackzampolin?

We have this for tests on gaia and now on SDK too (sim cli tests). We don't have tags based builds for releases but should be similar and easy
