### ISSUE TITLE
ids: more friendly string representation

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#727]
For all of the IDs, make a more friendly string representation.  Most important is to have the account address format rather than hex.

For example, logs say things like this:

```
I[2020-07-01|21:30:37.501] shutting down module=bidengine-order order="{Owner:9F97543245F06F406D82D0D92D3D74337484A143 DSeq:14690 GSeq:1 OSeq:1}"
```

The `Owner` field above should be represented as `akash1n7t4gvj97ph5qmvz6rvj60t5xd6gfg2rm5dh6x`.

Secondly, it would be better to have things in [path](https://github.com/ovrclk/akash/blob/3310cc668be406a19029ce458831a53f16345198/x/market/query/path.go#L36) format:

`"akash1n7t4gvj97ph5qmvz6rvj60t5xd6gfg2rm5dh6x/14690/1/1"`

**Comment by Ropes** [comment]
Implemented a pretty printer in the `sdkutil` package, everything looks nice in the tests when the global config is set via:
```go
	config := sdk.GetConfig()
	config.SetBech32PrefixForAccount("akash", "akash")
	config.Seal()
```
However when tests are run outside of that package, they'll show `cosmos` as the address denom. So tests will look a little funky for all types which get the stringer implementation.

Still need to implement a lot of String()'er interfaces.

**Comment by boz** [comment]
Can you call [`common.InitSDKConfig()`](https://github.com/ovrclk/akash/blob/c5cf6e255ca506a88fb387c4a65ff87c5ee4dbf1/cmd/common/sdk.go#L19) from `testutil.init()`?  It might cause circular dependencies, not sure.

It's really not important, tho - the bech32 prefixes don't matter in tests AFAIK.

**Comment by Ropes** [comment]
How to best edit the global config for testing is still a little bit of a head scratcher, but logs now look like this:
```
I[2020-07-08|17:03:30.204] group fetched                                module=bidengine-order order=akash1un2hh75y0nqrg0fz035cg3spcphe78jhrwmr68/1/1/1
D[2020-07-08|17:03:30.204] reservation requested                        module=provider-cluster cmp=service cmp=inventory-service order=akash1un2hh75y0nqrg0fz035cg3spcphe78jhrwmr68/1/1/1 resources=akash1un2hh75y0nqrg0fz035cg3spcphe78jhrwmr68/1/1
I[2020-07-08|17:03:30.204] reserve requested                            module=bidengine-order order=akash1un2hh75y0nqrg0fz035cg3spcphe78jhrwmr68/1/1/1
```

```
// Format: [Owner AccAddress]/[DSeq]/[GSeq]/[OSeq]/[Provider AccAddress]
// eg: akash1vgv30hr8lel8r7270wywmak5c82es3njws3u4z/795423625/1/1/akash1pxqksfr60zc6uadht6300uavwl3s58ct0apt9w
```
Or for a DeploymentID's String: `akash16wcjul5ekz3v7lw7e4l424c0quch72ycu308ju/2117345153`.
