### ISSUE TITLE
provider attributes: don't allow duplicate keys

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#728]
Right now, providers are allowed to have duplicate attributes.  This doesn't make sense because if either value doesn't match the required attribute then [`MatchAttributes()`](https://github.com/ovrclk/akash/blob/3310cc668be406a19029ce458831a53f16345198/x/deployment/types/types.go#L93-L104) will fail.

**Comment by novy4** [comment]
that's what I pointed in the RIOT chat, that's not ok...
