### ISSUE TITLE
deployment orders: add and handle ttl

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#76]
deployment orders should only be open for a some constant number of blocks.

order matching should run after this ttl.

**Comment by aastein** [comment]
what is `ttl`?

Is the idea of the second sentence to aggregate bids over the same block period?

**Comment by boz** [comment]
Time To Live - an order should stay open for x blocks.  x is implicitly 1 right now.

**Comment by aastein** [comment]
Should this be set in the genesis file?

**Comment by boz** [comment]
it was originally on the deployment (group)

**Comment by aastein** [comment]
I'm going to implement this by adding a ttl field and EXPIRED state to Order and Group.
