### ISSUE TITLE
adjust token unit: `uakt`

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#771]
The units we store are micro-akt; akt * 10^-6.

In all config files in this repo and elsewhere (github.com/ovrclk/docs, github.com/ovrclk/operations), change the unit from `akash` to `uakt`.

@jackzampolin is the cosmos unit `ucosmos`?  Will apps "just know" how to deal with `u`?

**Comment by jackzampolin** [comment]
The cosmos unit is uatom and lunie et al expect this and can deal with it.

**Comment by hydrogen18** [comment]
I've looked through ovrclk/akash and I'm not seeing many references to this deprecated unit. I'm checking the other projects now.

**Comment by hydrogen18** [comment]
After looking through the repos you indicated I am only seeing this one file still using "akt" and it is a test

https://github.com/ovrclk/akash/blob/master/sdl/coin_test.go

When I looked through the docs everywhere I found coins being used it showed "uakt"
