### ISSUE TITLE
provider sdl validation

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#778]
Validate SDL upon retrieval.  Some validations:

1. if [`DEPLOYMENT_INGRESS_STATIC_HOSTS`](https://github.com/ovrclk/akash/blob/faf26a8704ecf39730597254b9633d3da6542ca7/provider/cluster/kube/settings.go#L18-L20) is `false` then services [must have a host](https://github.com/ovrclk/akash/blob/faf26a8704ecf39730597254b9633d3da6542ca7/manifest/types.go#L67).
1. Don't allow clobbering of existing ingress hosts
1. Add a configurable set of disallowed user-supplied hosts.

**Comment by boz** [comment]
> 1. If a bid is cancelled due to hostname collision, stop bidding on orders from that addr in the network for some time period. Effective, but kind of dumb IMHO.

Yes we could do that or ignore the deployment and/or group.

> 2. Include a 32 bit hash of each hostname in the deployment (on the blockchain) and check that against the existing hosts before bidding. This increases the amount of data on the blockchain and is not perfect, for example hash collisions could cause a false positive
> 
I like this idea.  I think we should consider it, but let's look at the various name service protocols in the cosmos space that we might be able to leverage first.

===

I think that in the case of a hostname conflict, we should just reject the manifest - return an error during send-manifest - and leave it up to the user to update the deployment or close the lease.

We definitely need the other two things too tho:

* static/configurable hostname blacklist
* validation

**Comment by hydrogen18** [comment]
When you say " various name service protocols in the cosmos space" what are you referring to?

**Comment by hydrogen18** [comment]
Next step on this is to check in the handler for send-manifest if there is a hostname conflict and reject the manifest there with appropriate error code
