### ISSUE TITLE
bug: inventory resources are not updates after reserve release

### ISSUE THREAD

**Issue by troian** [ovrclk/akash#787]
Node resources are not updated on reserver event. same seem to happens with unreserve signal.
note: will be fixed as part of the SDL update

**Comment by hydrogen18** [comment]
@troian  it looks like this may have been fixed here https://github.com/ovrclk/akash/commit/a64ca04ad9218d06dab286c94c76b40f6606346f#diff-2b3feaa73af2b179a1fd81234bc35deed01d35995e53d5ee772470d193edccdfR325 . Do you agree?

**Comment by troian** [comment]
yah, that change fixed it

**Comment by hydrogen18** [comment]
Alright I'm going to go ahead and close this then since it doesn't look like there is anything left to do.
