### ISSUE TITLE
order sequence numbers: high chance of consensus confusion

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#80]
The facilitator engine cannot modify the state.  At the same time, it needs to emit deployment order transactions with a correct sequence number.

The sequence is currently based on the deployment.  This sequence is also used for deployment groups.  This all leads to the possibility of sequence generation being out of sync and consensus taking forever or impossible.

A quick fix might be to have a sequence for each deployment group.

**Comment by gosuri** [comment]
moved to _docs
