### ISSUE TITLE
disfix JSON wrapper errors revealed on validate-genesis

### ISSUE THREAD

**Issue by jbn** [ovrclk/akash#827]
### Issue type

Bug on Build

### Akash version

Branches `v0.8.1` and `v0.8.2`

### What happened

`akashd validate-genesis` returns,

```
ERROR: error validating genesis file /root/.akashd/config/genesis.json: failed to unmarshal auth genesis state: cannot parse isfix JSON wrapper: json: cannot unmarshal string into Go value of type amino.disfixWrapper
```

### What did you expect to happen

No error

### How to reproduce it

[Dockerfile Gist](https://gist.github.com/jbn/e1346d02f94fc8357eaa69ef1ee9caa5)

### Environment

- Debian Stretch
- golang 1.14.9
- Akash v0.8.1

**Comment by troian** [comment]
@jbn genesis in docker example is not for akashnet-1 chain. pull [this version](https://raw.githubusercontent.com/ovrclk/net/master/akashnet-1/genesis.json)
