### ISSUE TITLE
Circulating Supply REST Endpoint

### ISSUE THREAD

**Issue by gosuri** [ovrclk/akash#866]
we need circulating supply for Coingecko and CMC feeds, will be great to add [Kava's vesting module](https://github.com/Kava-Labs/kava/blob/master/x/validator-vesting/client/rest/query.go) and make it accessible over `/supply/circulating`

`Circulating Supply = Unlocked Vested Tokens + Staking Rewards`

**Comment by boz** [comment]
Done on a branch - this ticket can track merging that branch into master.
