### ISSUE TITLE
deployment: wait for leases

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#87]
Add a `--wait` flag or some such so that `photon deploy` prints back market activity until all leases have been generated for the deployment.

This is somewhat related to #77 because {order,fulfillment,lease} IDs are prefixed with the deployment address and the transactions that create them will include tags with these IDs.

For instance, both fulfillment and lease IDs have this structure:

```
{deployment-address}{group-id}{order-id}{provider-address}
```

For a given deployment with address `X`, we should be able to listen for all `CreateFulfillment` transactions whose fullfillment address begins with `X`.

We can probably do it without #77 but it will not be pretty and will likely take up more of our time debugging than just putting some effort in up front to make it less janky.

**Comment by aastein** [comment]
print orders too or just fulfillment and lease?
