### ISSUE TITLE
Generate command line documentation for "akash" from cobra.Command instances

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#887]
With the functionality of both binaries merged into one, we need to create command line level documentation for the `akash` command. Cobra can already generate help messages (e.g. running `akash help`) so we should be able to generate markdown that can be fed into the `ovrclk/docs` project. That way we don't have to go about updating the documentation manually each time we change something.

**Comment by hydrogen18** [comment]
Looks like the cobra author has an example of how to do this 

https://github.com/spf13/cobra/blob/master/doc/md_docs.md

I'm trying it now.

**Comment by boz** [comment]
Honestly I don't know how useful a dump of -h for every command is

**Comment by boz** [comment]
The signal:noise is very low and if people are using the cli anyways then they should just use --help themselves.

Maybe it'd be useful as a source to pull a curated subset from.

The real challenge with docs is making them readable and useable IMO

**Comment by hydrogen18** [comment]
The other possibility here is to augment this information with the name of each environmental variable the application understands, since it isn't really listed anywhere in the help output.

**Comment by hydrogen18** [comment]
I experimented a bit with this and it is really simple to do. If we decide we want to feed some of the information into the docs let me know.

**Comment by boz** [comment]
Okay. I realized it'd be nice to point people to the cli docs for commands.  Maybe it'll force us to populate our long descriptions well too.
