### ISSUE TITLE
kind Docker image repository clarity

### ISSUE THREAD

**Issue by Ropes** [ovrclk/akash#917]
@hydrogen18 gave us a clean make target to load custom(akash) Docker images into a kind cluster environment: https://github.com/ovrclk/akash/blob/master/_run/common-kind.mk#L46-L48

However we're now facing some confusion as to what is the best practice for getting locally built/custom docker images into the `kind` environment for testing. 

`kind` will emulate k8s behavior, and pull from global repositories like DockerHub if the image is not found in its registry.

From the docs:
```
Note: The Kubernetes default pull policy is IfNotPresent unless the image tag is :latest in which case the default policy is Always. IfNotPresent causes the Kubelet to skip pulling an image if it already exists. If you want those images loaded into node to work as expected, please:

don't use a :latest tag
and / or:

specify imagePullPolicy: IfNotPresent or imagePullPolicy: Never on your container(s).
https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
```

It's difficult to reason on how strictly kind behaves like k8s, but if it were 1:1. If you're trying to debug a tagged build, say v0.9.0, push it into kind, and then launch the container. Then rebuild a new image with that same tag, k8s would not pull a new image into the node's docker registry, because the image already exists and doesn't need to be pulled. 

Unless the pull policy is `Always`, which we could make default for our test environment pod definitions. 

## Action Items
* [ ] Determine best pattern to build local image, push into kind, and reference from deployment declaration.
* [ ] Update documentation
* [ ] Implement changes

Related: https://github.com/ovrclk/akash/pull/910

**Comment by boz** [comment]
For dev environments, what about using `Never` and a vanity image like `ovrclk.dev/akash:dev`?

Then you can "push" to that tag and bounce pods to update.
