### ISSUE TITLE
Add telemetry to handlers

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#921]
Add [telemetry](https://docs.cosmos.network/master/core/telemetry.html) to handlers so we can have insight into how the network is performing.   Things like:

* deployment created
* order created
* order closed
* lease created
* x amount transferred
* gauge for open orders 
* gauge for active leases
* etc...

**Comment by hydrogen18** [comment]
For provider metrics, does it make sense to use Cosmos SDK stuff for this kind of data? I know the provider is sort of governed by the blockchain, but the actual process of managing a deployment isn't really coupled to the blockchain.

**Comment by boz** [comment]
For provider services stuff no, it doesn't - but this ticket was for blockchain stuff.
