### ISSUE TITLE
group state: require user intervention before creating second order

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#944]
Leases can be closed in a number of ways, one of which is by the provider closing the bid.  In this case, the group for for the lease is set back to "open" state, which means that a new order for the lease will be created.

This is problematic because if an owner is not actively watching, they will not know that they should push their manifest to the new leaseholder.  Instead, the group should go into a "paused" state that the owner can then start again if/when they choose to.

* [group returning to order state](https://github.com/ovrclk/akash/blob/c6a3e29889ac1b48d829231246430492e36035bd/x/deployment/keeper/keeper.go#L228-L233)
* [closing bid triggers above](https://github.com/ovrclk/akash/blob/c6a3e29889ac1b48d829231246430492e36035bd/x/market/handler/msg_server.go#L107)

**Comment by troian** [comment]
ref #944
