### ISSUE TITLE
virtual machine dev environment

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#968]
We need a VM development dev environment so that we can test on something that more closely resembles production.

Minikube _might_ do the trick, but ideally we'd be using our kubespray automation.

**Comment by hydrogen18** [comment]
So what are we aiming to run inside of a VM as part of this? Kubernetes? K8S ? Calico networking enabled on K8S?

**Comment by boz** [comment]
Yes.

Kubernetes = k8s

Perhaps running minikube instead of KinD would be a good start, but the idea is to bootstrap a k8s cluster in a Vm with the same tooling that we use in production to bootstrap a k8s cluster, and then run a provider in the created cluster.

The goal is to create a replacement for KinD that is more similar to our k8s clusters on packet.

Does that make sense?

**Comment by hydrogen18** [comment]
Yeah I think we can do that, we will probably leave the provider running on the host machine for simplicity.

**Comment by boz** [comment]
> leave the provider running on the host machine for simplicity.

That would be a great start; it'd be the `_run/kube` analogy.

**Comment by boz** [comment]
Also I think that we should continue to have `kind` as an option unless the VM method is as quick to spin up as `kind` (historically it's been much slower.)

**Comment by hydrogen18** [comment]
I read up some on Kubespray and it seems simple enough to get started with.

So apparently you need to have 2GB of memory for a master node, & 1GB of memory for a worker node. If we run a single master & 2 workers we'd need about 4 GB of memory to host such a thing in VMs.

Presumably we can use something like VirtualBox to host such a test environment consisting of multiple VMs and a private network. VirtualBox runs well enough on Linux & Macs but isn't available in Github CI.
