### ISSUE TITLE
leases status: address not included for non-http ports

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#979]
An address to connect to is not included in the lease-status response when there are not any http ports:

```json
{
  "services": {
    "akash": {
      "name": "akash",
      "available": 1,
      "total": 1,
      "uris": null,
      "observed-generation": 0,
      "replicas": 0,
      "updated-replicas": 0,
      "ready-replicas": 0,
      "available-replicas": 0
    }
  },
  "forwarded-ports": {
    "akash": [
      {
        "port": 26657,
        "externalPort": 32061,
        "proto": "TCP",
        "available": 1,
        "name": "akash"
      }
    ]
  }
}
```

**Comment by hydrogen18** [comment]
The provider status should show this information.

**Comment by boz** [comment]
It does, but it's cumbersome to use (it has a scheme), and it's not really the same thing conceptually.   The endpoint for these might be a different endpoint than the provider gateway is hosted on.

**Comment by hydrogen18** [comment]
No, that isn't accurate. It's returned in the status here

https://github.com/ovrclk/akash/blame/master/provider/service.go#L155

It needs to be configured via this flag or the appropriate env. var.

https://github.com/ovrclk/akash/blob/master/provider/cmd/run.go#L143

**Comment by boz** [comment]
Ah, I forgot about that setting and thought you were talking about `akash query provider`.  Thanks.

Yes, that will do for now I think, but we should have this field be associated with the lease endpoints and not the provider as a whole.

**Comment by hydrogen18** [comment]
We can also return this data with the endpoint data for a lease if that makes sense.

Right now 1 provider manages 1 kubernetes cluster (as far as I know) so it should be the same address across all leases. If IP traffic reaches any node, it gets sent to the appropriate node by some kubernetes magic.

**Comment by boz** [comment]
There can be different endpoints for the same cluster, consider the case when we allow IP leasing whole IP addresses.

I'll modify my PR for this to use the setting that you mentioned, I think that will be good enough for now.
