### ISSUE TITLE
tests failing from cosmos-sdk: `t.TmpDir` not defined

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#997]
Not sure what is going on here.  They may be using a newer version of `go`, but I don't think that we updated the cosmos-sdk version lately?

```
vendor/github.com/cosmos/cosmos-sdk/testutil/network/network.go:172:34: t.TempDir undefined (type *testing.T has no field or method TempDir)
```

**Comment by anilCSE** [comment]
@boz please update your golang version. Required version `15.x`
