### ISSUE TITLE
the "provider send-manifest" response should indicate what the provider did with the manifest

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#999]
Right now the `provider send-manifest` sends a manifest to a provider. If the manifest is valid, the provider responds with 200. We should also add information as to if the manifest matched a deployment that the provider has a lease for. It's easy to accidentally do `provider send-manifest` to the wrong provider & have nothing at all happen. This isn't a good experience for users.

**Comment by boz** [comment]
@hydrogen18 should we close this?

**Comment by hydrogen18** [comment]
I merged a fix for this, closing.
